<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Source\Awaiten.SourceGenerators\Awaiten.SourceGenerators.csproj"/>
		<ProjectReference Include="..\..\Source\Awaiten\Awaiten.csproj"/>
		<ProjectReference Include="..\Awaiten.Tests.Support\Awaiten.Tests.Support.csproj"/>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
	</ItemGroup>

</Project>
