using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Awaiten.SourceGenerators.Tests;

/// <summary>
///     Pins that the consumer-side markers (<c>[Arg]</c>, <c>[FromKey]</c>, <c>[Inject]</c>) ship as
///     source-injected <see langword="internal" /> polyfills rather than public runtime types, so an assembly
///     that uses them carries no runtime reference to <c>Awaiten</c> - only the build-only analyzer reference.
/// </summary>
public class MarkerAttributesTests
{
	private const string Consumer =
		"""
		using Awaiten;

		namespace MyCode;

		public sealed class Dep { }

		public sealed class Service
		{
			public Service([Arg] int amount, [FromKey("primary")] Dep dep) { }

			[Inject]
			public Dep? Extra { get; set; }
		}

		[Container]
		[Transient<Service>]
		[Singleton<Dep>(Key = "primary")]
		[Singleton<Dep>]
		public static partial class MyContainer
		{
		}
		""";

	[Fact]
	public async Task PostInitializationSource_IsEmitted_AndDeclaresTheMarkersInternal()
	{
		GeneratorResult result = Generator.Run(Consumer);

		await That(result.Sources).ContainsKey("__AwaitenRuntimeMarkers.g.cs");
		string markers = result.Sources["__AwaitenRuntimeMarkers.g.cs"];

		await That(markers).Contains("// <auto-generated/>");
		await That(markers).Contains("internal sealed class ArgAttribute");
		await That(markers).Contains("internal sealed class FromKeyAttribute");
		await That(markers).Contains("internal sealed class InjectAttribute");
	}

	[Fact]
	public async Task Markers_AreNeverEmittedAsPublic()
	{
		GeneratorResult result = Generator.Run(Consumer);
		string markers = result.Sources["__AwaitenRuntimeMarkers.g.cs"];

		await That(markers).DoesNotContain("public sealed class ArgAttribute");
		await That(markers).DoesNotContain("public sealed class FromKeyAttribute");
		await That(markers).DoesNotContain("public sealed class InjectAttribute");
	}

	[Fact]
	public async Task GeneratedContainer_HasNoRuntimeReferenceToTheMarkerTypes()
	{
		GeneratorResult result = Generator.Run(Consumer);
		string container = result.Sources["Awaiten.MyCode.MyContainer.g.cs"];

		// Keys are emitted as literals and [Arg]/[Inject] shape the emitted code without naming the attribute
		// types, so the container source never mentions them - it would not compile if it did (the types are
		// internal to another assembly).
		await That(container).DoesNotContain("ArgAttribute");
		await That(container).DoesNotContain("FromKeyAttribute");
		await That(container).DoesNotContain("InjectAttribute");
	}

	[Fact]
	public async Task MarkerTypes_ResolveToTheInjectedInternalCopy_NotTheAwaitenRuntimeAssembly()
	{
		(Compilation output, _) = Generator.RunGenerator(Consumer, additionalReferences: [], assemblyTypes: []);

		foreach (string metadataName in new[] { "Awaiten.ArgAttribute", "Awaiten.FromKeyAttribute", "Awaiten.InjectAttribute" })
		{
			INamedTypeSymbol? symbol = output.GetTypeByMetadataName(metadataName);

			await That(symbol).IsNotNull().Because($"the generator injects {metadataName} as source");
			await That(symbol!.DeclaredAccessibility).IsEqualTo(Accessibility.Internal);

			// The consumer compilation references the Awaiten runtime assembly, yet the marker resolves to the
			// injected copy in the consumer's own assembly - proof the runtime no longer carries these types.
			await That(symbol.ContainingAssembly.Name).IsEqualTo("TestAssembly")
				.Because("the marker is the source-injected internal polyfill, not a runtime type");
			await That(symbol.ContainingAssembly.Name).IsNotEqualTo("Awaiten");
		}
	}

	[Fact]
	public async Task InjectedMarkers_CompileUnderCSharp73()
	{
		// The markers target "old TFM, no runtime reference" consumers. A post-init source parses with the
		// consumer's LangVersion, and a plain net48/netstandard2.0 project defaults to C# 7.3, so the emitted
		// source must be free of any newer-C# construct (no #nullable, init, records or file-scoped namespaces).
		string markers = Generator.Run(Consumer).Sources["__AwaitenRuntimeMarkers.g.cs"];

		Microsoft.CodeAnalysis.SyntaxTree tree = CSharpSyntaxTree.ParseText(
			markers, new CSharpParseOptions(LanguageVersion.CSharp7_3),
			cancellationToken: TestContext.Current.CancellationToken);
		CSharpCompilation compilation = CSharpCompilation.Create(
			"MarkerProbe",
			[tree,],
			References.For([]),
			new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

		string[] errors = compilation.GetDiagnostics(TestContext.Current.CancellationToken)
			.Where(d => d.Severity == DiagnosticSeverity.Error)
			.Select(d => d.ToString())
			.ToArray();

		await That(errors).IsEmpty();
	}
}
