<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>Microsoft.Extensions.DependencyInjection interop for Awaiten.</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Awaiten\Awaiten.csproj" />
		<ProjectReference Include="..\Awaiten.SourceGenerators\Awaiten.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

</Project>
