using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Awaiten.SourceGenerators;

partial class AwaitenGenerator
{
	/// <summary>
	///     The hint name of the post-initialization source that injects the consumer-side marker attributes. It
	///     deliberately avoids the <c>Awaiten.{typePath}.g.cs</c> shape the container emitter uses, so a
	///     <c>[Container]</c> named <c>__Markers</c> in the global namespace cannot collide with it.
	/// </summary>
	internal const string MarkersHintName = "__AwaitenRuntimeMarkers.g.cs";

	/// <summary>
	///     The three consumer-side marker attributes - <c>[Arg]</c>, <c>[FromKey]</c> and <c>[Inject]</c> - injected
	///     as <see langword="internal" /> polyfills into every compilation the generator runs over (the
	///     <c>IsExternalInit</c> pattern). They are compile-time-only inputs the generator reads by fully-qualified
	///     metadata name, so shipping them as source rather than as public runtime types means an assembly that uses
	///     only these markers carries no runtime reference to <c>Awaiten</c> - only the build-only analyzer reference.
	///     Classification matches them by metadata name and is accessibility-agnostic, so the generator behavior is
	///     identical whether the type is public-in-Awaiten or internal-in-the-consumer.
	/// </summary>
	private const string MarkersSource =
		"""
		// <auto-generated/>
		namespace Awaiten
		{
			/// <summary>
			///     Marks a constructor parameter as supplied at resolve time rather than from the object graph. A service
			///     with one or more <c>[Arg]</c> parameters is parameterized: it is built fresh on every request and is
			///     resolvable only through a <c>Func&lt;TArg…, TService&gt;</c> whose leading type arguments are the runtime
			///     arguments, matched positionally to the marked parameters. The remaining parameters resolve from the graph.
			/// </summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
			internal sealed class ArgAttribute : global::System.Attribute
			{
			}

			/// <summary>
			///     Selects the keyed registration of a constructor parameter's or injected property's service type.
			///     The dependency is resolved from the registration whose <c>Key</c> matches <see cref="Key" />
			///     rather than the unkeyed one.
			/// </summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
			internal sealed class FromKeyAttribute : global::System.Attribute
			{
				/// <param name="key">The resolution key to select.</param>
				public FromKeyAttribute(string key) => Key = key;

				/// <summary>
				///     Selects the keyed registration under a non-string constant key - an enum value
				///     (<c>[FromKey(PaymentProvider.Stripe)]</c>) or a <c>typeof(...)</c>. Enum keys refactor safely and make
				///     typos compile errors, unlike string keys.
				/// </summary>
				/// <param name="key">The resolution key to select.</param>
				public FromKeyAttribute(object key) => Key = key;

				/// <summary>The resolution key to select.</summary>
				public object Key { get; }
			}

			/// <summary>
			///     Marks a settable or <c>init</c> property to be filled from the object graph after construction.
			///     Property injection is opt-in: only a property carrying this attribute is filled. The property's
			///     service type is resolved like a constructor parameter (direct, <c>Func&lt;T&gt;</c> / <c>Lazy&lt;T&gt;</c>,
			///     a collection, or a keyed registration via <c>[FromKey]</c>) and assigned through an object initializer,
			///     so no reflection is used and the instance is never observed half-set. A <see cref="Deferred" /> property
			///     is instead assigned after construction to break a mutual cycle. By default the property is required:
			///     an unregistered service type reports <c>AWT101</c>, like a missing constructor parameter. Mark it
			///     <see cref="Optional" /> to leave it unassigned when nothing is registered.
			/// </summary>
			/// <remarks>
			///     The property needs a <c>set</c> or <c>init</c> accessor (otherwise <c>AWT136</c>). <c>[Arg]</c> is not
			///     valid on an injected property (<c>AWT137</c>); runtime arguments flow only through a <c>Func&lt;…&gt;</c>
			///     factory into constructor parameters. A plain property edge participates fully in cycle (<c>AWT102</c>),
			///     captive (<c>AWT105</c>) and async-initialization analysis, like a constructor parameter. Only constructed
			///     instances are filled; a factory or pre-built-instance registration is produced whole by its source.
			/// </remarks>
			[global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
			internal sealed class InjectAttribute : global::System.Attribute
			{
				/// <summary>
				///     Defers the property's assignment until after the owning instance is constructed and cached,
				///     instead of filling it in the object initializer. A deferred property carries no cycle edge, so it
				///     can break a mutual constructor cycle: two singletons that reference each other through a deferred
				///     property are both constructed and cached first, then wired up. It still participates in captive
				///     (<c>AWT105</c>) and async-initialization analysis.
				/// </summary>
				public bool Deferred { get; set; }

				/// <summary>
				///     Makes the dependency optional: when its service type is not registered the property is left at its
				///     default instead of reporting <c>AWT101</c>. When the dependency is registered an optional property is
				///     filled exactly like a required one, so <c>Optional</c> only changes what happens when nothing is registered.
				/// </summary>
				public bool Optional { get; set; }
			}
		}

		""";

	/// <summary>
	///     Registers the consumer-side marker attributes as post-initialization source, so they exist in every
	///     compilation the generator runs over without the consumer referencing the <c>Awaiten</c> runtime assembly.
	/// </summary>
	private static void RegisterMarkerAttributes(IncrementalGeneratorPostInitializationContext context)
		=> context.AddSource(MarkersHintName, SourceText.From(MarkersSource, Encoding.UTF8));
}
