using System.Text;
using Awaiten.SourceGenerators.Internals;

namespace Awaiten.SourceGenerators;

/// <summary>
///     Emits the generated members of a container from its <see cref="ContainerModel" />: a base
///     <c>Scope</c> type holding the resolution logic (scoped instances, transient construction, synchronous
///     disposal) and a sealed <c>Root</c> subclass owning the thread-safe singletons. The <c>[Container]</c>
///     class itself is a static definition and carries no generated state. Enclosing types are re-opened as
///     <c>partial</c> so the container can be a nested type. Per-instance members are named after the
///     implementation type (e.g. <c>ResolveGreeter</c>, <c>_greeter</c>), with a numeric suffix added
///     only when two implementations would otherwise collide.
/// </summary>
internal static class Emitter
{
	public static string Emit(ContainerModel model)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();

		int depth = 0;
		bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
		if (hasNamespace)
		{
			builder.Append("namespace ").AppendLine(model.Namespace);
			builder.AppendLine("{");
			depth++;
		}

		foreach (TypeDeclaration containing in model.ContainingTypes.AsArray())
		{
			Indent(builder, depth).Append("partial ").Append(containing.Keyword).Append(' ').AppendLine(containing.Name);
			Indent(builder, depth).AppendLine("{");
			depth++;
		}

		Indent(builder, depth).Append("static partial class ").AppendLine(model.TypeName);
		Indent(builder, depth).AppendLine("{");

		if (model.HasErrors)
		{
			EmitErrorBody(builder, depth + 1, model.TypeName);
		}
		else
		{
			Names names = Names.Build(model.Instances.AsArray());
			Dictionary<string, int> serviceToIndex = BuildServiceMap(model);
			EmitContainerBody(builder, depth + 1, model, names, serviceToIndex);
		}

		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < model.ContainingTypes.Count; i++)
		{
			depth--;
			Indent(builder, depth).AppendLine("}");
		}

		if (hasNamespace)
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	private static Dictionary<string, int> BuildServiceMap(ContainerModel model)
	{
		Dictionary<string, int> serviceToIndex = new(StringComparer.Ordinal);
		InstanceModel[] instances = model.Instances.AsArray();
		for (int i = 0; i < instances.Length; i++)
		{
			foreach (string service in instances[i].ServiceTypes.AsArray())
			{
				serviceToIndex[service] = i;
			}
		}

		return serviceToIndex;
	}

	/// <summary>
	///     Each registered service type paired with the instance that produces it, deduplicated on the service
	///     type. Registrations are coalesced upstream so service types are already unique, but deduping here
	///     keeps the typed base list and its explicit implementations in lockstep: a duplicate base or a
	///     duplicate explicit implementation would each fail to compile, so neither must be emitted twice.
	///     A parameterized service is excluded: it is not directly resolvable (only through its
	///     <c>Func&lt;TArg…, T&gt;</c> factory), so it gets no typed resolution fast path.
	/// </summary>
	private static IEnumerable<(string Service, int Index)> UniqueServices(InstanceModel[] instances, bool strict)
	{
		HashSet<string> seen = new(StringComparer.Ordinal);
		for (int i = 0; i < instances.Length; i++)
		{
			// A parameterized service has no typed fast path; a strictly-withheld disposable service is reached
			// only through Owned<T>, so it gets none either.
			if (instances[i].IsParameterized || IsWithheld(instances[i], strict))
			{
				continue;
			}

			foreach (string service in instances[i].ServiceTypes.AsArray().Where(seen.Add))
			{
				yield return (service, i);
			}
		}
	}

	/// <summary>
	///     Appends <c>, global::Awaiten.IAwaitenResolver&lt;S&gt;</c> for each registered service type to a
	///     just-written base list, so the scope (and its root) exposes a typed resolution fast path.
	/// </summary>
	private static void EmitGenericResolverBases(StringBuilder builder, InstanceModel[] instances, bool strict)
	{
		foreach ((string service, int _) in UniqueServices(instances, strict))
		{
			builder.Append(", global::Awaiten.IAwaitenResolver<").Append(service).Append('>');
		}
	}

	/// <summary>
	///     Emits the explicit <c>IAwaitenResolver&lt;S&gt;.Resolve()</c> implementation for each registered
	///     service type, delegating to that instance's resolver method. Only the explicitly registered service
	///     types get a typed path; the synthetic <c>Func&lt;T&gt;</c>/<c>Lazy&lt;T&gt;</c> relationship entries
	///     remain reachable through the Type-based dispatch table.
	/// </summary>
	private static void EmitGenericResolverImpls(StringBuilder builder, int depth, InstanceModel[] instances, Names names, bool strict)
	{
		foreach ((string service, int index) in UniqueServices(instances, strict))
		{
			Indent(builder, depth).Append(service).Append(" global::Awaiten.IAwaitenResolver<")
				.Append(service).Append(">.Resolve() => ").Append(names.Resolver(index)).AppendLine("();");
		}
	}

	/// <summary>
	///     Emits a generic <c>Resolve&lt;T&gt;()</c> instance method on the owner. Called through the concrete
	///     (sealed) container or scope, the <c>this is IAwaitenResolver&lt;T&gt;</c> test dispatches to the
	///     typed resolver; relationship types and unregistered services fall back to the Type-based path.
	/// </summary>
	private static void EmitGenericResolveMethod(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("public T Resolve<T>()");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("if (this is global::Awaiten.IAwaitenResolver<T> __typed)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("return __typed.Resolve();");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("return (T)Resolve(typeof(T));");
		Indent(builder, depth).AppendLine("}");
	}

	private static void EmitContainerBody(StringBuilder builder, int depth, ContainerModel model, Names names, Dictionary<string, int> serviceToIndex)
	{
		InstanceModel[] instances = model.Instances.AsArray();

		// The [Container] class is a pure static definition: it carries the registration attributes and any
		// static factory or instance members they name, and holds the generated Scope/Root types - nothing
		// generated lives on it directly. All state and resolution live on those types: the base Scope holds
		// the static dispatch table plus scoped/transient logic and delegates singletons to the root, while
		// the sealed Root subclass owns the singletons and is the usable instance (new MyContainer.Root()).
		EmitRootClass(builder, depth, instances, names, serviceToIndex);
		builder.AppendLine();
		EmitScopeBaseClass(builder, depth, instances, names, serviceToIndex, model.Strict);
	}

	// A disposable build-on-demand service (a disposable transient or parameterized service) is withheld from
	// the public by-type resolution surface under strict lifetime safety: its bare type and plain Func factory
	// are no longer dispatchable (they throw a guidance exception) and it gets no typed resolver, so the only
	// ways to reach it are constructor injection and Owned<T> / Func<…, Owned<T>>.
	private static bool IsWithheld(InstanceModel instance, bool strict)
		=> strict && instance.IsDisposable && (instance.Lifetime == Lifetime.Transient || instance.IsParameterized);

	private static bool IsRootOwned(InstanceModel instance)
		=> instance.Lifetime == Lifetime.Singleton || instance.Production == ProductionKind.Instance;

	// The guidance thrown when a withheld service is requested by type under strict lifetime safety.
	private static string WithheldThrow(string service)
	{
		string display = service.Replace("global::", string.Empty);
		return $"throw new global::System.InvalidOperationException(\"Awaiten: '{display}' is a disposable service withheld from by-type resolution under strict lifetime safety; obtain it through Owned<{display}> or Func<…, Owned<{display}>>, inject it directly, or set LifetimeSafety.Loose on the [Container].\")";
	}

	/// <summary>
	///     Emits the reverse-order drain of the (possibly null) <c>__toDispose</c> list captured under the
	///     lock - disposing what the owner created, newest first.
	/// </summary>
	private static void EmitDrainDisposables(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("if (__toDispose is not null)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("for (int __index = __toDispose.Count - 1; __index >= 0; __index--)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("if (__toDispose[__index] is global::System.IDisposable __disposable)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).AppendLine("__disposable.Dispose();");
		Indent(builder, depth + 2).AppendLine("}");
		Indent(builder, depth + 1).AppendLine("}");
		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the base <c>Scope</c>: the single home of resolution logic. It caches scoped instances on
	///     itself, constructs transients, and resolves singletons through <c>protected virtual</c> delegators
	///     that the <c>Root</c> subclass overrides. Child (request) scopes are instances of this type.
	/// </summary>
	private static void EmitScopeBaseClass(StringBuilder builder, int depth, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex, bool strict)
	{
		Indent(builder, depth).Append("public class Scope : global::Awaiten.IAwaitenScope");
		EmitGenericResolverBases(builder, instances, strict);
		builder.AppendLine();
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		// The dispatch table lives on the Scope (the only reader, through TryResolve); it is static, so it is
		// built once for the whole container, and reached by simple name from this type and its Root subclass.
		List<DispatchEntry> entries = BuildDispatchEntries(instances, names, strict);
		if (entries.Count > 0)
		{
			EmitDispatchTable(builder, body, entries);
			builder.AppendLine();
		}

		// The (sealed) root scope this scope resolves singletons through. Holding the root directly lets a
		// child scope reach a singleton with a devirtualized call instead of a virtual override dispatch; it
		// is the root itself on the Root subclass, and shared down every child scope.
		Indent(builder, body).AppendLine("protected readonly Root __root;");
		// Synchronization is on a private gate object rather than the owner instance: a Scope/Root is
		// publicly reachable, and locking on it would let consumer code (lock (scope)) interfere with
		// resolution and disposal. The disposables list is created lazily on first use. These are protected
		// so the Root subclass's singleton overrides share the same gate and list.
		Indent(builder, body).AppendLine("protected readonly object __gate = new object();");
		Indent(builder, body).AppendLine("protected volatile bool __disposed;");
		Indent(builder, body).AppendLine("protected global::System.Collections.Generic.List<object>? __disposables;");
		EmitCacheFields(builder, body, instances, names, Lifetime.Scoped);
		builder.AppendLine();
		// The root is its own __root (this parameterless ctor is only ever reached through Root's base call,
		// so the cast always holds); child scopes are handed the shared root. The child ctor is private so a
		// scope is only ever created through CreateScope(), never hand-built with a borrowed root.
		Indent(builder, body).AppendLine("private protected Scope()");
		Indent(builder, body).AppendLine("{");
		Indent(builder, body + 1).AppendLine("__root = (Root)this;");
		Indent(builder, body).AppendLine("}");
		builder.AppendLine();
		Indent(builder, body).AppendLine("private Scope(Root root)");
		Indent(builder, body).AppendLine("{");
		Indent(builder, body + 1).AppendLine("__root = root;");
		Indent(builder, body).AppendLine("}");
		builder.AppendLine();
		EmitResolutionApi(builder, body, instances, names, strict);
		builder.AppendLine();
		EmitGenericResolveMethod(builder, body);
		builder.AppendLine();
		// A scope is the single source of scopes: nesting shares the same root (and therefore the same
		// singletons), so a child created from a child is no different from one created from the root. A
		// child scope's lifetime is owned by its caller; the parent does not track it. The concrete return
		// type spares callers holding a Scope an interface hop; the interface contract is met explicitly.
		Indent(builder, body).AppendLine("public Scope CreateScope() => new Scope(__root);");
		Indent(builder, body).AppendLine("global::Awaiten.IAwaitenScope global::Awaiten.IAwaitenScope.CreateScope() => CreateScope();");

		if (instances.Length > 0)
		{
			builder.AppendLine();
			EmitOwnedHelper(builder, body);
		}

		builder.AppendLine();
		EmitGenericResolverImpls(builder, body, instances, names, strict);

		for (int i = 0; i < instances.Length; i++)
		{
			builder.AppendLine();
			EmitScopeResolver(builder, body, i, instances[i], instances, names, serviceToIndex);
		}

		builder.AppendLine();
		EmitDispose(builder, body);

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the <c>Root</c>: the root scope where singletons (and pre-built Instances) physically live,
	///     and the usable container instance (<c>new MyContainer.Root()</c>). It overrides the base's virtual
	///     singleton delegators with the real caching/member access, so a child scope delegating through
	///     <c>__root</c> lands here.
	/// </summary>
	private static void EmitRootClass(StringBuilder builder, int depth, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		Indent(builder, depth).AppendLine("public sealed class Root : Scope");
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		EmitCacheFields(builder, body, instances, names, Lifetime.Singleton);
		builder.AppendLine();
		Indent(builder, body).AppendLine("public Root() : base()");
		Indent(builder, body).AppendLine("{");
		Indent(builder, body).AppendLine("}");

		for (int i = 0; i < instances.Length; i++)
		{
			// A parameterized service is never cached on the root; its single fresh-per-call resolver lives
			// on the base Scope (protected) and the Root inherits it.
			if (instances[i].IsParameterized
			    || (instances[i].Lifetime != Lifetime.Singleton && instances[i].Production != ProductionKind.Instance))
			{
				continue;
			}

			builder.AppendLine();
			EmitRootResolver(builder, body, i, instances[i], instances, names, serviceToIndex);
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the volatile cache fields for instances of the given lifetime (reference-type fields are
	///     volatile so the lock-free fast path cannot observe a non-null reference before the constructor's
	///     writes are visible on weak memory models such as arm64). A pre-built Instance has no field.
	/// </summary>
	private static void EmitCacheFields(StringBuilder builder, int depth, InstanceModel[] instances, Names names, Lifetime lifetime)
	{
		for (int i = 0; i < instances.Length; i++)
		{
			InstanceModel instance = instances[i];
			// A pre-built Instance has no field, and a parameterized service is rebuilt per call from its
			// runtime arguments and so is never cached.
			if (instance.Production == ProductionKind.Instance || instance.IsParameterized || instance.Lifetime != lifetime)
			{
				continue;
			}

			string modifier = instance.IsReferenceType ? "private volatile " : "private ";
			Indent(builder, depth).Append(modifier).Append(instance.ImplementationType)
				.Append("? ").Append(names.Field(i)).AppendLine(";");
		}
	}

	private static void EmitDisposedGuard(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("if (__disposed)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("throw new global::System.ObjectDisposedException(GetType().FullName);");
		Indent(builder, depth).AppendLine("}");
	}

	private static void EmitResolutionApi(StringBuilder builder, int depth, InstanceModel[] instances, Names names, bool strict)
	{
		List<DispatchEntry> entries = BuildDispatchEntries(instances, names, strict);

		Indent(builder, depth).AppendLine("public object Resolve(global::System.Type serviceType)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("if (TryResolve(serviceType, out object? instance))");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("return instance!;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine(
			"throw new global::System.InvalidOperationException($\"No registration for type '{serviceType}' on this container.\");");
		Indent(builder, depth).AppendLine("}");
		builder.AppendLine();

		Indent(builder, depth).AppendLine("public bool TryResolve(global::System.Type serviceType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance)");
		Indent(builder, depth).AppendLine("{");
		if (entries.Count == 0)
		{
			Indent(builder, depth + 1).AppendLine("instance = null;");
			Indent(builder, depth + 1).AppendLine("return false;");
			Indent(builder, depth).AppendLine("}");
			return;
		}

		Indent(builder, depth + 1).AppendLine("if (__dispatch.TryGetValue(serviceType, out int __case))");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("switch (__case)");
		Indent(builder, depth + 2).AppendLine("{");
		for (int i = 0; i < entries.Count; i++)
		{
			// A withheld service's case throws a guidance exception instead of producing an instance, so the
			// type stays known (a helpful error) rather than silently reading as "no registration".
			if (entries[i].Throws)
			{
				Indent(builder, depth + 3).Append("case ").Append(i).Append(": ").Append(entries[i].Value).AppendLine(";");
			}
			else
			{
				Indent(builder, depth + 3).Append("case ").Append(i).Append(": instance = ")
					.Append(entries[i].Value).AppendLine("; return true;");
			}
		}

		Indent(builder, depth + 2).AppendLine("}");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("instance = null;");
		Indent(builder, depth + 1).AppendLine("return false;");
		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     The ordered dispatch cases for an owner: each registered service type mapped to its resolver
	///     call, plus the relationship types <c>Func&lt;T&gt;</c> and <c>Lazy&lt;T&gt;</c> over it (a fresh
	///     factory/lazy bound to this owner's resolver). The order is identical on the container and its
	///     scope, so a single static table built on the container is valid for both.
	/// </summary>
	private static List<DispatchEntry> BuildDispatchEntries(InstanceModel[] instances, Names names, bool strict)
	{
		List<DispatchEntry> entries = new();
		HashSet<string> seen = new(StringComparer.Ordinal);

		// Explicit service registrations first, so a directly registered relationship type (e.g. a
		// registered Lazy<T>) wins the dispatch slot over the synthetic relationship entry below. Service
		// types are unique across instances (registrations are coalesced), so each is added exactly once.
		// Seeding 'seen' here lets the synthetic pass skip any key an explicit registration already claimed.
		for (int i = 0; i < instances.Length; i++)
		{
			AddServiceEntries(instances[i], names.Resolver(i), entries, seen, strict);
		}

		// Synthetic Func<T>/Lazy<T> over each service, skipping any key an explicit registration already
		// claimed so the static dispatch table never contains a duplicate key (which would otherwise throw
		// from the dictionary initializer at runtime). A parameterized service is skipped: its only entry is
		// the Func<TArg…, T> added above.
		for (int i = 0; i < instances.Length; i++)
		{
			if (!instances[i].IsParameterized)
			{
				AddRelationshipEntries(instances[i], names.Resolver(i), entries, seen, strict);
			}
		}

		return entries;
	}

	/// <summary>
	///     Adds the directly-dispatchable entry for each of an instance's service types: a parameterized
	///     service contributes only its <c>Func&lt;TArg…, T&gt;</c> factory (its bare type cannot be built
	///     without the runtime arguments); any other service maps to its resolver call.
	/// </summary>
	private static void AddServiceEntries(InstanceModel instance, string resolver, List<DispatchEntry> entries, HashSet<string> seen, bool strict)
	{
		bool withheld = IsWithheld(instance, strict);
		bool rootOwned = IsRootOwned(instance);
		string[] argTypes = instance.ArgTypes();
		foreach (string service in instance.ServiceTypes.AsArray())
		{
			if (argTypes.Length > 0)
			{
				// The plain Func<TArg…, T> factory accumulates on the owner; under strict safety it is withheld
				// (throws guidance) so only the Owned form below can build the disposable parameterized service.
				string parameterizedFunc = $"global::System.Func<{string.Join(", ", argTypes)}, {service}>";
				seen.Add(parameterizedFunc);
				entries.Add(withheld
					? new DispatchEntry(parameterizedFunc, WithheldThrow(service), true)
					: new DispatchEntry(parameterizedFunc, FuncFactory(argTypes, service, resolver)));

				// The leak-free factory for a parameterized service: Func<TArg…, Owned<T>> hands each built
				// instance back as a disposal handle instead of accumulating it on the owner.
				string parameterizedOwnedFunc = $"global::System.Func<{string.Join(", ", argTypes)}, global::Awaiten.Owned<{service}>>";
				seen.Add(parameterizedOwnedFunc);
				entries.Add(new DispatchEntry(parameterizedOwnedFunc, OwnedFuncFactory(argTypes, service, resolver, rootOwned)));
				continue;
			}

			seen.Add(service);
			// A strictly-withheld disposable transient's bare type is no longer dispatchable; resolving it by
			// type throws guidance (reachable only by injection or Owned<T>).
			entries.Add(withheld
				? new DispatchEntry(service, WithheldThrow(service), true)
				: new DispatchEntry(service, resolver + "()"));
		}
	}

	/// <summary>
	///     Adds the synthetic <c>Func&lt;T&gt;</c> and <c>Lazy&lt;T&gt;</c> entries over each of an instance's
	///     service types, skipping any key an explicit registration already claimed (tracked in
	///     <paramref name="seen" />) so the dispatch table never contains a duplicate key.
	/// </summary>
	private static void AddRelationshipEntries(InstanceModel instance, string resolver, List<DispatchEntry> entries, HashSet<string> seen, bool strict)
	{
		bool withheld = IsWithheld(instance, strict);
		bool rootOwned = IsRootOwned(instance);
		foreach (string service in instance.ServiceTypes.AsArray())
		{
			// The plain Func<T> factory accumulates on its owner; under strict safety it is withheld (throws
			// guidance), leaving Func<Owned<T>> as the leak-free way to build the disposable on demand.
			string func = $"global::System.Func<{service}>";
			if (seen.Add(func))
			{
				entries.Add(withheld
					? new DispatchEntry(func, WithheldThrow(service), true)
					: new DispatchEntry(func, $"new global::System.Func<{service}>(() => {resolver}())"));
			}

			// Lazy<T> is memoized - it builds at most once and never accumulates - so it stays resolvable even
			// for a withheld disposable service.
			string lazy = $"global::System.Lazy<{service}>";
			if (seen.Add(lazy))
			{
				entries.Add(new DispatchEntry(lazy, $"new global::System.Lazy<{service}>(() => {resolver}())"));
			}

			// Owned<T> hands the caller a disposal handle over a single resolution; Func<Owned<T>> is the
			// leak-free factory that produces one per call. Both build into a throwaway child scope, and both
			// stay resolvable under strict safety - they are the sanctioned way to reach a withheld service.
			string owned = $"global::Awaiten.Owned<{service}>";
			if (seen.Add(owned))
			{
				entries.Add(new DispatchEntry(owned, OwnedBare(service, resolver, rootOwned)));
			}

			string ownedFunc = $"global::System.Func<{owned}>";
			if (seen.Add(ownedFunc))
			{
				entries.Add(new DispatchEntry(ownedFunc, OwnedFuncFactory([], service, resolver, rootOwned)));
			}
		}
	}

	/// <summary>
	///     Emits the static <c>__dispatch</c> table mapping each service type to its case number. It lives on
	///     the base <c>Scope</c> and is <c>static</c>, so it is built once and shared by every scope and the
	///     <c>Root</c> subclass that inherits it.
	/// </summary>
	private static void EmitDispatchTable(StringBuilder builder, int depth, List<DispatchEntry> entries)
	{
		Indent(builder, depth).AppendLine(
			"private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> __dispatch = new global::System.Collections.Generic.Dictionary<global::System.Type, int>");
		Indent(builder, depth).AppendLine("{");
		for (int i = 0; i < entries.Count; i++)
		{
			Indent(builder, depth + 1).Append("{ typeof(").Append(entries[i].Type).Append("), ").Append(i).AppendLine(" },");
		}

		Indent(builder, depth).AppendLine("};");
	}

	/// <summary>
	///     Emits a resolver on the base <c>Scope</c>. A parameterized service (with <c>[Arg]</c> parameters)
	///     takes those runtime arguments and is built fresh per call (regardless of its declared lifetime),
	///     so it lives here as a <c>protected</c> method the <c>Root</c> can also call. Otherwise
	///     singleton-owned services (singletons and pre-built Instances) become a <c>protected virtual</c>
	///     delegator to <c>__root</c> (overridden by the <c>Root</c>); scoped services cache on the scope;
	///     transients construct fresh.
	/// </summary>
	private static void EmitScopeResolver(StringBuilder builder, int depth, int index, InstanceModel instance, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		string type = instance.ImplementationType;
		string resolver = names.Resolver(index);

		if (instance.IsParameterized)
		{
			string[] argTypes = instance.ArgTypes();
			string signature = string.Join(", ", argTypes.Select((t, i) => $"{t} a{i}"));
			string parameterizedConstruction = EmitConstruction(instance, instances, names, serviceToIndex);
			// Reachable from the Root (a singleton's Func<TArg…, T> binds it there) and from a throwaway
			// Owned<T> scope built off any owner (__s.ResolveX(args)), so it is internal rather than protected -
			// protected would not be callable through a base-typed scope reference from the derived Root (CS1540).
			EmitFreshResolver(builder, depth, new FreshResolver("internal", type, resolver, signature, parameterizedConstruction, instance.IsDisposable));
			return;
		}

		if (instance.Lifetime == Lifetime.Singleton || instance.Production == ProductionKind.Instance)
		{
			Indent(builder, depth).Append("protected virtual ").Append(type).Append(' ').Append(resolver).AppendLine("()");
			Indent(builder, depth).AppendLine("{");
			EmitDisposedGuard(builder, depth + 1);
			Indent(builder, depth + 1).Append("return __root.").Append(resolver).AppendLine("();");
			Indent(builder, depth).AppendLine("}");
			return;
		}

		string construction = EmitConstruction(instance, instances, names, serviceToIndex);

		// Transient and scoped resolvers are internal (not private) so a throwaway Owned<T> scope can call them
		// directly through a base-typed scope reference (__s.ResolveX()) - this bypasses the strict by-type
		// withholding, which only blocks the public dispatch/typed surface, not these resolver methods.
		if (instance.Lifetime == Lifetime.Transient)
		{
			EmitFreshResolver(builder, depth, new FreshResolver("internal", type, resolver, string.Empty, construction, instance.IsDisposable));
			return;
		}

		EmitCachingResolver(builder, depth, new CachingResolver("internal", type, resolver, names.Field(index), construction, instance.IsDisposable, "// Scoped: one instance per scope."));
	}

	/// <summary>
	///     Emits a resolver that constructs a fresh instance on every call (a transient, or a parameterized
	///     service that also takes the runtime arguments named in its signature). A disposable instance is
	///     registered for teardown on the owner under the lock, re-checking <c>__disposed</c> so one built
	///     during a concurrent dispose is disposed here rather than leaked.
	/// </summary>
	private static void EmitFreshResolver(StringBuilder builder, int depth, in FreshResolver resolver)
	{
		string type = resolver.Type;
		string construction = resolver.Construction;
		Indent(builder, depth).Append(resolver.Modifiers).Append(' ').Append(type).Append(' ').Append(resolver.Method)
			.Append('(').Append(resolver.Signature).AppendLine(")");
		Indent(builder, depth).AppendLine("{");
		EmitDisposedGuard(builder, depth + 1);
		if (resolver.Disposable)
		{
			Indent(builder, depth + 1).Append(type).Append(" created = ").Append(construction).AppendLine(";");
			Indent(builder, depth + 1).AppendLine("lock (__gate)");
			Indent(builder, depth + 1).AppendLine("{");
			Indent(builder, depth + 2).AppendLine("if (__disposed)");
			Indent(builder, depth + 2).AppendLine("{");
			Indent(builder, depth + 3).AppendLine("((global::System.IDisposable)created).Dispose();");
			Indent(builder, depth + 3).AppendLine("throw new global::System.ObjectDisposedException(GetType().FullName);");
			Indent(builder, depth + 2).AppendLine("}");
			builder.AppendLine();
			Indent(builder, depth + 2).AppendLine("(__disposables ??= new global::System.Collections.Generic.List<object>()).Add(created);");
			Indent(builder, depth + 1).AppendLine("}");
			builder.AppendLine();
			Indent(builder, depth + 1).AppendLine("return created;");
		}
		else
		{
			Indent(builder, depth + 1).Append("return ").Append(construction).AppendLine(";");
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits a singleton resolver on the <c>Root</c> as a <c>protected override</c>: a pre-built Instance
	///     returns the static container member by simple name; a constructed/factory singleton is cached once
	///     under the lock.
	/// </summary>
	private static void EmitRootResolver(StringBuilder builder, int depth, int index, InstanceModel instance, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		string type = instance.ImplementationType;
		string resolver = names.Resolver(index);

		if (instance.Production == ProductionKind.Instance)
		{
			// The container is a static class, so its pre-built instance member is in scope by simple name.
			Indent(builder, depth).Append("protected override ").Append(type).Append(' ').Append(resolver).AppendLine("()");
			Indent(builder, depth).AppendLine("{");
			EmitDisposedGuard(builder, depth + 1);
			Indent(builder, depth + 1).Append("return ").Append(instance.ProductionMember).AppendLine(";");
			Indent(builder, depth).AppendLine("}");
			return;
		}

		string construction = EmitConstruction(instance, instances, names, serviceToIndex);
		EmitCachingResolver(builder, depth, new CachingResolver("protected override", type, resolver, names.Field(index), construction, instance.IsDisposable, null));
	}

	/// <summary>
	///     Emits a lock-free-read, lock-on-write cached resolver: return the cached field if set, otherwise
	///     construct once under <c>lock (__gate)</c>, registering a disposable instance for teardown.
	/// </summary>
	private static void EmitCachingResolver(StringBuilder builder, int depth, in CachingResolver resolver)
	{
		if (resolver.Comment is not null)
		{
			Indent(builder, depth).AppendLine(resolver.Comment);
		}

		Indent(builder, depth).Append(resolver.Modifiers).Append(' ').Append(resolver.Type).Append(' ').Append(resolver.Method).AppendLine("()");
		Indent(builder, depth).AppendLine("{");
		EmitDisposedGuard(builder, depth + 1);
		Indent(builder, depth + 1).Append("if (").Append(resolver.Field).AppendLine(" is not null)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).Append("return ").Append(resolver.Field).AppendLine(";");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("lock (__gate)");
		Indent(builder, depth + 1).AppendLine("{");
		EmitDisposedGuard(builder, depth + 2);
		Indent(builder, depth + 2).Append("if (").Append(resolver.Field).AppendLine(" is null)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).Append(resolver.Field).Append(" = ").Append(resolver.Construction).AppendLine(";");
		if (resolver.Disposable)
		{
			Indent(builder, depth + 3).Append("(__disposables ??= new global::System.Collections.Generic.List<object>()).Add(").Append(resolver.Field).AppendLine(");");
		}

		Indent(builder, depth + 2).AppendLine("}");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).Append("return ").Append(resolver.Field).AppendLine(";");
		Indent(builder, depth).AppendLine("}");
	}

	private static string EmitConstruction(InstanceModel instance, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		ParameterModel[] parameters = instance.ConstructorParameters.AsArray();
		StringBuilder arguments = new();
		int argIndex = 0;
		for (int p = 0; p < parameters.Length; p++)
		{
			if (p > 0)
			{
				arguments.Append(", ");
			}

			// Runtime arguments are passed in as a0, a1, … by the parameterized resolver; the rest resolve
			// from the graph.
			arguments.Append(parameters[p].Kind == DependencyKind.Arg
				? "a" + argIndex++
				: ResolveExpression(parameters[p], instances, names, serviceToIndex));
		}

		if (instance.Production == ProductionKind.Factory)
		{
			// The container is a static class nested-enclosing both Scope and Root, so its static factory
			// method is in scope by simple name - no receiver.
			return $"{instance.ProductionMember}({arguments})";
		}

		return $"new {instance.ImplementationType}({arguments})";
	}

	/// <summary>
	///     The expression that supplies a single constructor argument. The target resolves through its own
	///     resolver - read straight off <c>__root</c> for a singleton/pre-built instance (a devirtualized
	///     call), or by simple name for a scoped/transient (its resolver is <c>internal</c> on the base
	///     <c>Scope</c>, reachable from the <c>Root</c> too). A relationship type wraps the target in a
	///     deferred <c>Func&lt;T&gt;</c> / <c>Lazy&lt;T&gt;</c>.
	/// </summary>
	private static string ResolveExpression(ParameterModel parameter, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		int targetIndex = serviceToIndex[parameter.ServiceType];
		string resolver = names.Resolver(targetIndex);
		InstanceModel target = instances[targetIndex];

		string[] funcArgTypes = parameter.FuncArgTypes.AsArray();
		bool rootOwned = IsRootOwned(target);

		// Owned relationships build into a throwaway child scope, independent of this owner, so they need none
		// of the root-routing below: a Func<…, Owned<T>> factory, or a bare Owned<T> resolved once.
		if (parameter.ProducesOwned)
		{
			return OwnedFuncFactory(funcArgTypes, parameter.ServiceType, resolver, rootOwned);
		}

		if (parameter.Kind == DependencyKind.Owned)
		{
			return OwnedBare(parameter.ServiceType, resolver, rootOwned);
		}

		if (parameter.Kind == DependencyKind.Func && funcArgTypes.Length > 0)
		{
			// A Func<TArg…, T> over a parameterized service binds the owner's parameterized resolver, which
			// takes the runtime arguments and is never cached - so the root routing below does not apply (the
			// protected resolver is reachable from the Root directly).
			return FuncFactory(funcArgTypes, parameter.ServiceType, resolver);
		}

		string value;
		if (rootOwned)
		{
			// Read singletons straight off the (sealed) root scope so the dependency call devirtualizes,
			// rather than dispatching through this scope's virtual delegator. On the root, __root is itself.
			value = $"__root.{resolver}()";
		}
		else
		{
			// A root-owned owner can only capture a non-singleton through a relationship (a direct capture
			// would be a captive dependency). The target's scoped/transient resolver is internal on the base
			// Scope, so it is reachable by simple name from the Root too - call it directly. Routing through the
			// generic Resolve<T>() instead would hit the by-type withholding under strict lifetime safety and
			// throw when a Lazy<DisposableTransient> held by a singleton is forced.
			value = $"{resolver}()";
		}

		return parameter.Kind switch
		{
			DependencyKind.Func => $"new global::System.Func<{parameter.ServiceType}>(() => {value})",
			DependencyKind.Lazy => $"new global::System.Lazy<{parameter.ServiceType}>(() => {value})",
			_ => value,
		};
	}

	/// <summary>
	///     A <c>new Func&lt;TArg…, T&gt;((a0, …) =&gt; resolver(a0, …))</c> expression that forwards the
	///     runtime arguments to a parameterized service's resolver. With no argument types this is the plain
	///     deferred <c>Func&lt;T&gt;</c>.
	/// </summary>
	private static string FuncFactory(string[] argTypes, string service, string resolver)
	{
		string generics = argTypes.Length == 0 ? service : string.Join(", ", argTypes) + ", " + service;
		string lambdaArgs = string.Join(", ", argTypes.Select((_, i) => "a" + i));
		return $"new global::System.Func<{generics}>(({lambdaArgs}) => {resolver}({lambdaArgs}))";
	}

	/// <summary>
	///     Emits the <c>__Owned&lt;T&gt;</c> helper on the base <c>Scope</c>: it opens a throwaway child scope
	///     (sharing the root's singletons), resolves a single <c>T</c> into it through the supplied delegate and
	///     returns an <c>Owned&lt;T&gt;</c> over that scope. Disposing the handle disposes only that scope,
	///     draining what was built for this one resolution while shared singletons live on.
	/// </summary>
	private static void EmitOwnedHelper(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("protected global::Awaiten.Owned<T> __Owned<T>(global::System.Func<Scope, T> __resolve)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("Scope __owned = CreateScope();");
		Indent(builder, depth + 1).AppendLine("return new global::Awaiten.Owned<T>(__owned, __resolve(__owned));");
		Indent(builder, depth).AppendLine("}");
	}

	// A bare Owned<T>: resolve T once into a throwaway child scope and wrap it as a disposal handle.
	private static string OwnedBare(string service, string resolver, bool rootOwned)
		=> $"__Owned<{service}>({OwnedInner(service, resolver, [], rootOwned)})";

	/// <summary>
	///     A <c>new Func&lt;TArg…, Owned&lt;T&gt;&gt;((a0, …) =&gt; __Owned&lt;T&gt;(…))</c> expression: each call
	///     builds <c>T</c> in a throwaway child scope and hands back the disposal handle.
	/// </summary>
	private static string OwnedFuncFactory(string[] argTypes, string service, string resolver, bool rootOwned)
	{
		string owned = $"global::Awaiten.Owned<{service}>";
		string generics = argTypes.Length == 0 ? owned : string.Join(", ", argTypes) + ", " + owned;
		string lambdaArgs = string.Join(", ", argTypes.Select((_, i) => "a" + i));
		return $"new global::System.Func<{generics}>(({lambdaArgs}) => __Owned<{service}>({OwnedInner(service, resolver, argTypes, rootOwned)}))";
	}

	/// <summary>
	///     The delegate passed to <c>__Owned&lt;T&gt;</c> that resolves the single value into the throwaway
	///     scope <c>__s</c>. A root-owned target (a singleton or pre-built instance) goes through the public
	///     typed surface (it is never withheld, and shares off the root); any other target calls its resolver
	///     directly - which is internal so it stays reachable even when the type is withheld from by-type
	///     resolution under strict lifetime safety.
	/// </summary>
	private static string OwnedInner(string service, string resolver, string[] argTypes, bool rootOwned)
	{
		if (rootOwned)
		{
			return $"__s => __s.Resolve<{service}>()";
		}

		string lambdaArgs = string.Join(", ", argTypes.Select((_, i) => "a" + i));
		return $"__s => __s.{resolver}({lambdaArgs})";
	}

	private static void EmitDispose(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("public void Dispose()");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("global::System.Collections.Generic.List<object>? __toDispose;");
		Indent(builder, depth + 1).AppendLine("lock (__gate)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("if (__disposed)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).AppendLine("return;");
		Indent(builder, depth + 2).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 2).AppendLine("__disposed = true;");
		// Hand off the list rather than copying it: nulling the field releases ownership without allocating.
		Indent(builder, depth + 2).AppendLine("__toDispose = __disposables;");
		Indent(builder, depth + 2).AppendLine("__disposables = null;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		// Dispose outside the lock so user code does not run under the lock.
		EmitDrainDisposables(builder, depth + 1);
		Indent(builder, depth).AppendLine("}");
	}

	private static void EmitErrorBody(StringBuilder builder, int depth, string typeName)
	{
		string message =
			$"\"Awaiten: container '{typeName}' has registration errors; see the build diagnostics (AWT1xx).\"";
		// The container has registration errors, so emit a throwing Root that still satisfies the shape
		// consumers depend on (new MyContainer.Root(), Resolve, CreateScope, Dispose). This keeps the build
		// focused on the actionable AWT diagnostics rather than cascading "type not found" errors.
		Indent(builder, depth).AppendLine("public sealed class Root : global::Awaiten.IAwaitenScope");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).Append(
				"public object Resolve(global::System.Type serviceType) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public bool TryResolve(global::System.Type serviceType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("instance = null;");
		Indent(builder, depth + 2).AppendLine("return false;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::Awaiten.IAwaitenScope CreateScope() => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public void Dispose() { }");
		Indent(builder, depth).AppendLine("}");
	}

	private static StringBuilder Indent(StringBuilder builder, int depth)
	{
		for (int i = 0; i < depth; i++)
		{
			builder.Append('\t');
		}

		return builder;
	}

	/// <summary>
	///     The inputs to <see cref="EmitCachingResolver" />: the method <see cref="Modifiers" /> and return
	///     <see cref="Type" />, the resolver <see cref="Method" /> name and backing <see cref="Field" />, the
	///     <see cref="Construction" /> expression, whether the instance <see cref="Disposable">needs disposal</see>,
	///     and an optional leading <see cref="Comment" />.
	/// </summary>
	private readonly struct CachingResolver(string modifiers, string type, string method, string field, string construction, bool disposable, string? comment)
	{
		public string Modifiers { get; } = modifiers;

		public string Type { get; } = type;

		public string Method { get; } = method;

		public string Field { get; } = field;

		public string Construction { get; } = construction;

		public bool Disposable { get; } = disposable;

		public string? Comment { get; } = comment;
	}

	/// <summary>
	///     The inputs to <see cref="EmitFreshResolver" />: the method <see cref="Modifiers" /> and return
	///     <see cref="Type" />, the resolver <see cref="Method" /> name, its parameter <see cref="Signature" />
	///     (empty for a transient, the runtime arguments for a parameterized service), the
	///     <see cref="Construction" /> expression and whether the instance <see cref="Disposable">needs
	///     disposal</see>.
	/// </summary>
	private readonly struct FreshResolver(string modifiers, string type, string method, string signature, string construction, bool disposable)
	{
		public string Modifiers { get; } = modifiers;

		public string Type { get; } = type;

		public string Method { get; } = method;

		public string Signature { get; } = signature;

		public string Construction { get; } = construction;

		public bool Disposable { get; } = disposable;
	}

	/// <summary>
	///     A single dispatch case: the service <see cref="Type" /> requested and the <see cref="Value" />
	///     assigned to <c>instance</c> (the resolver call). When <see cref="Throws" /> is set, <see cref="Value" />
	///     is instead a <c>throw</c> expression and the case throws rather than producing an instance - used for
	///     a service withheld from by-type resolution under strict lifetime safety.
	/// </summary>
	private readonly struct DispatchEntry(string type, string value, bool throws = false)
	{
		public string Type { get; } = type;

		public string Value { get; } = value;

		public bool Throws { get; } = throws;
	}

	/// <summary>
	///     Assigns each instance a readable resolver method name (<c>ResolveGreeter</c>) and cache
	///     field name (<c>_greeter</c>) derived from the implementation's simple type name, appending a
	///     numeric suffix only when two implementations would otherwise collide (case-insensitively).
	/// </summary>
	private sealed class Names
	{
		private readonly string[] _fields;
		private readonly string[] _resolvers;

		private Names(string[] resolvers, string[] fields)
		{
			_resolvers = resolvers;
			_fields = fields;
		}

		public string Resolver(int index) => _resolvers[index];

		public string Field(int index) => _fields[index];

		public static Names Build(InstanceModel[] instances)
		{
			string[] resolvers = new string[instances.Length];
			string[] fields = new string[instances.Length];
			HashSet<string> used = new(StringComparer.OrdinalIgnoreCase);

			for (int i = 0; i < instances.Length; i++)
			{
				string baseName = Sanitize(instances[i].Name);
				string name = baseName;
				int suffix = 2;
				while (!used.Add(name))
				{
					name = baseName + suffix;
					suffix++;
				}

				resolvers[i] = "Resolve" + name;
				fields[i] = "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);
			}

			return new Names(resolvers, fields);
		}

		private static string Sanitize(string name)
		{
			if (string.IsNullOrEmpty(name))
			{
				return "Service";
			}

			StringBuilder builder = new(name.Length);
			foreach (char c in name.Where(c => char.IsLetterOrDigit(c) || c == '_'))
			{
				builder.Append(c);
			}

			if (builder.Length == 0 || (!char.IsLetter(builder[0]) && builder[0] != '_'))
			{
				builder.Insert(0, '_');
			}

			return builder.ToString();
		}
	}
}
