using System.Text;
using Awaiten.SourceGenerators.Internals;

namespace Awaiten.SourceGenerators;

/// <summary>
///     Emits the <c>partial class</c> implementation of a container from its
///     <see cref="ContainerModel" />: thread-safe singletons, a nested <c>Scope</c> type for scoped
///     instances, transient construction, and synchronous disposal. Enclosing types are re-opened as
///     <c>partial</c> so the container can be a nested type. Per-instance members are named after the
///     implementation type (e.g. <c>ResolveGreeter</c>, <c>_greeter</c>), with a numeric suffix added
///     only when two implementations would otherwise collide.
/// </summary>
internal static class Emitter
{
	public static string Emit(ContainerModel model)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();

		int depth = 0;
		bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
		if (hasNamespace)
		{
			builder.Append("namespace ").AppendLine(model.Namespace);
			builder.AppendLine("{");
			depth++;
		}

		foreach (TypeDeclaration containing in model.ContainingTypes.AsArray())
		{
			Indent(builder, depth).Append("partial ").Append(containing.Keyword).Append(' ').AppendLine(containing.Name);
			Indent(builder, depth).AppendLine("{");
			depth++;
		}

		Indent(builder, depth).Append("partial class ").Append(model.TypeName)
			.AppendLine(" : global::Awaiten.IAwaitenContainer");
		Indent(builder, depth).AppendLine("{");

		if (model.HasErrors)
		{
			EmitErrorBody(builder, depth + 1, model.TypeName);
		}
		else
		{
			Names names = Names.Build(model.Instances.AsArray());
			Dictionary<string, int> serviceToIndex = BuildServiceMap(model);
			EmitContainerBody(builder, depth + 1, model, names, serviceToIndex);
		}

		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < model.ContainingTypes.Count; i++)
		{
			depth--;
			Indent(builder, depth).AppendLine("}");
		}

		if (hasNamespace)
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	private static Dictionary<string, int> BuildServiceMap(ContainerModel model)
	{
		Dictionary<string, int> serviceToIndex = new(StringComparer.Ordinal);
		InstanceModel[] instances = model.Instances.AsArray();
		for (int i = 0; i < instances.Length; i++)
		{
			foreach (string service in instances[i].ServiceTypes.AsArray())
			{
				serviceToIndex[service] = i;
			}
		}

		return serviceToIndex;
	}

	/// <summary>
	///     Appends <c>, global::Awaiten.IAwaitenResolver&lt;S&gt;</c> for each registered service type to a
	///     just-written base list, so the container and its scope expose a typed resolution fast path. Service
	///     types are unique across instances (registrations are coalesced), but the set guards against an
	///     accidental duplicate base which would not compile.
	/// </summary>
	private static void EmitGenericResolverBases(StringBuilder builder, ContainerModel model)
	{
		HashSet<string> seen = new(StringComparer.Ordinal);
		foreach (InstanceModel instance in model.Instances.AsArray())
		{
			// A parameterized service is not directly resolvable (only through its Func<TArg…, T> factory),
			// so it gets no typed resolution fast path.
			if (IsParameterized(instance))
			{
				continue;
			}

			foreach (string service in instance.ServiceTypes.AsArray().Where(seen.Add))
			{
				builder.Append(", global::Awaiten.IAwaitenResolver<").Append(service).Append('>');
			}
		}
	}

	/// <summary>
	///     Emits the explicit <c>IAwaitenResolver&lt;S&gt;.Resolve()</c> implementation for each registered
	///     service type, delegating to that instance's resolver method. Only the explicitly registered service
	///     types get a typed path; the synthetic <c>Func&lt;T&gt;</c>/<c>Lazy&lt;T&gt;</c> relationship entries
	///     remain reachable through the Type-based dispatch table.
	/// </summary>
	private static void EmitGenericResolverImpls(StringBuilder builder, int depth, InstanceModel[] instances, Names names)
	{
		for (int i = 0; i < instances.Length; i++)
		{
			// A parameterized service has no typed resolver: its resolver takes the runtime arguments, so it
			// is reached only through its Func<TArg…, T> factory in the Type-based dispatch table.
			if (IsParameterized(instances[i]))
			{
				continue;
			}

			string resolver = names.Resolver(i);
			foreach (string service in instances[i].ServiceTypes.AsArray())
			{
				Indent(builder, depth).Append(service).Append(" global::Awaiten.IAwaitenResolver<")
					.Append(service).Append(">.Resolve() => ").Append(resolver).AppendLine("();");
			}
		}
	}

	/// <summary>
	///     Emits a generic <c>Resolve&lt;T&gt;()</c> instance method on the owner. Called through the concrete
	///     (sealed) container or scope, the <c>this is IAwaitenResolver&lt;T&gt;</c> test dispatches to the
	///     typed resolver; relationship types and unregistered services fall back to the Type-based path.
	/// </summary>
	private static void EmitGenericResolveMethod(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("public T Resolve<T>()");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("if (this is global::Awaiten.IAwaitenResolver<T> __typed)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("return __typed.Resolve();");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("return (T)Resolve(typeof(T));");
		Indent(builder, depth).AppendLine("}");
	}

	private static void EmitContainerBody(StringBuilder builder, int depth, ContainerModel model, Names names, Dictionary<string, int> serviceToIndex)
	{
		InstanceModel[] instances = model.Instances.AsArray();

		// The container is a facade: it owns only the static dispatch table and a lazily-created root scope,
		// and forwards the resolver surface (kept for the DI bridge) to it. All resolution lives in the nested
		// Scope hierarchy - the base Scope holds scoped/transient logic and delegates singletons to the root,
		// while the RootScope subclass owns the singletons. The dispatch table is read by the Scope through
		// the container type.
		List<DispatchEntry> entries = BuildDispatchEntries(instances, names);
		if (entries.Count > 0)
		{
			EmitDispatchTable(builder, depth, entries);
			builder.AppendLine();
		}

		Indent(builder, depth).AppendLine("private volatile bool __disposed;");
		Indent(builder, depth).AppendLine("private volatile Scope? __root;");
		builder.AppendLine();
		EmitRootProperty(builder, depth);
		builder.AppendLine();
		EmitContainerForwarding(builder, depth);
		builder.AppendLine();
		EmitContainerDispose(builder, depth);
		builder.AppendLine();
		EmitScopeBaseClass(builder, depth, model, instances, names, serviceToIndex);
		builder.AppendLine();
		EmitRootScopeClass(builder, depth, model, instances, names, serviceToIndex);
	}

	/// <summary>
	///     Emits the lazily-created root <c>Scope</c> property. The root is built on first use under the
	///     singleton gate (rather than in a constructor, which would clash with a user-defined one), and acts
	///     as the default scope that the container forwards to.
	/// </summary>
	private static void EmitRootProperty(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("public Scope Root");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("get");
		Indent(builder, depth + 1).AppendLine("{");
		// Guard against use after disposal here (not just in the resolvers): otherwise the lazy getter
		// would silently rebuild a fresh root scope on a disposed container.
		EmitDisposedGuard(builder, depth + 2);
		Indent(builder, depth + 2).AppendLine("Scope? __current = __root;");
		Indent(builder, depth + 2).AppendLine("if (__current is not null)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).AppendLine("return __current;");
		Indent(builder, depth + 2).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 2).AppendLine("lock (this)");
		Indent(builder, depth + 2).AppendLine("{");
		EmitDisposedGuard(builder, depth + 3);
		Indent(builder, depth + 3).AppendLine("return __root ??= new RootScope(this);");
		Indent(builder, depth + 2).AppendLine("}");
		Indent(builder, depth + 1).AppendLine("}");
		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the container's <c>IAwaitenContainer</c> surface as thin forwarders to the root scope. The
	///     public <c>CreateScope</c> returns the concrete <c>Scope</c> (so callers holding the container
	///     resolve through a sealed receiver); the interface contract is met explicitly.
	/// </summary>
	private static void EmitContainerForwarding(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("public object Resolve(global::System.Type serviceType) => Root.Resolve(serviceType);");
		Indent(builder, depth).AppendLine(
			"public bool TryResolve(global::System.Type serviceType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance) => Root.TryResolve(serviceType, out instance);");
		Indent(builder, depth).AppendLine("public Scope CreateScope() => Root.CreateScope();");
		Indent(builder, depth).AppendLine("global::Awaiten.IAwaitenScope global::Awaiten.IAwaitenContainer.CreateScope() => Root.CreateScope();");
	}

	/// <summary>
	///     Emits the container's disposal: it owns nothing but the root scope, so disposing the container
	///     disposes the root (which in turn disposes the singletons and the root's own scoped instances).
	/// </summary>
	private static void EmitContainerDispose(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("public void Dispose()");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("Scope? __rootToDispose;");
		Indent(builder, depth + 1).AppendLine("lock (this)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("if (__disposed)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).AppendLine("return;");
		Indent(builder, depth + 2).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 2).AppendLine("__disposed = true;");
		Indent(builder, depth + 2).AppendLine("__rootToDispose = __root;");
		Indent(builder, depth + 2).AppendLine("__root = null;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		// Dispose outside the lock so user code does not run under the lock.
		Indent(builder, depth + 1).AppendLine("__rootToDispose?.Dispose();");
		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the reverse-order drain of the (possibly null) <c>__toDispose</c> list captured under the
	///     lock - disposing what the owner created, newest first.
	/// </summary>
	private static void EmitDrainDisposables(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("if (__toDispose is not null)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("for (int __index = __toDispose.Count - 1; __index >= 0; __index--)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("if (__toDispose[__index] is global::System.IDisposable __disposable)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).AppendLine("__disposable.Dispose();");
		Indent(builder, depth + 2).AppendLine("}");
		Indent(builder, depth + 1).AppendLine("}");
		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the base <c>Scope</c>: the single home of resolution logic. It caches scoped instances on
	///     itself, constructs transients, and resolves singletons through <c>protected virtual</c> delegators
	///     that the <c>RootScope</c> subclass overrides. Child (request) scopes are instances of this type.
	/// </summary>
	private static void EmitScopeBaseClass(StringBuilder builder, int depth, ContainerModel model, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		Indent(builder, depth).Append("public class Scope : global::Awaiten.IAwaitenScope");
		EmitGenericResolverBases(builder, model);
		builder.AppendLine();
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		Indent(builder, body).Append("protected readonly ").Append(model.TypeName).AppendLine(" __container;");
		// Synchronization is on the owner instance itself (no separate gate object to allocate); the
		// disposables list is created lazily on first use. These are protected so the RootScope subclass's
		// singleton overrides share them.
		Indent(builder, body).AppendLine("protected volatile bool __disposed;");
		Indent(builder, body).AppendLine("protected global::System.Collections.Generic.List<object>? __disposables;");
		EmitCacheFields(builder, body, instances, names, Lifetime.Scoped);
		builder.AppendLine();
		Indent(builder, body).Append("public Scope(").Append(model.TypeName).AppendLine(" container) => __container = container;");
		builder.AppendLine();
		EmitResolutionApi(builder, body, instances, names, true, model.TypeName);
		builder.AppendLine();
		EmitGenericResolveMethod(builder, body);
		builder.AppendLine();
		// A scope is the single source of scopes: nesting shares the same container (and therefore the same
		// root singletons). A child scope's lifetime is owned by its caller; the parent does not track it.
		Indent(builder, body).AppendLine("public Scope CreateScope() => new Scope(__container);");
		builder.AppendLine();
		EmitGenericResolverImpls(builder, body, instances, names);

		for (int i = 0; i < instances.Length; i++)
		{
			builder.AppendLine();
			EmitScopeResolver(builder, body, i, instances[i], instances, names, serviceToIndex);
		}

		builder.AppendLine();
		EmitDispose(builder, body);

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the <c>RootScope</c>: the root scope where singletons (and pre-built Instances) physically
	///     live. It overrides the base's virtual singleton delegators with the real caching/member access, so
	///     a child scope delegating to <c>__container.Root</c> lands here.
	/// </summary>
	private static void EmitRootScopeClass(StringBuilder builder, int depth, ContainerModel model, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		Indent(builder, depth).AppendLine("public sealed class RootScope : Scope");
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		EmitCacheFields(builder, body, instances, names, Lifetime.Singleton);
		builder.AppendLine();
		Indent(builder, body).Append("public RootScope(").Append(model.TypeName).AppendLine(" container) : base(container)");
		Indent(builder, body).AppendLine("{");
		Indent(builder, body).AppendLine("}");

		for (int i = 0; i < instances.Length; i++)
		{
			// A parameterized service is never cached on the root; its single fresh-per-call resolver lives
			// on the base Scope (protected) and the RootScope inherits it.
			if (IsParameterized(instances[i])
			    || (instances[i].Lifetime != Lifetime.Singleton && instances[i].Production != ProductionKind.Instance))
			{
				continue;
			}

			builder.AppendLine();
			EmitRootResolver(builder, body, i, instances[i], instances, names, serviceToIndex);
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the volatile cache fields for instances of the given lifetime (reference-type fields are
	///     volatile so the lock-free fast path cannot observe a non-null reference before the constructor's
	///     writes are visible on weak memory models such as arm64). A pre-built Instance has no field.
	/// </summary>
	private static void EmitCacheFields(StringBuilder builder, int depth, InstanceModel[] instances, Names names, Lifetime lifetime)
	{
		for (int i = 0; i < instances.Length; i++)
		{
			InstanceModel instance = instances[i];
			// A pre-built Instance has no field, and a parameterized service is rebuilt per call from its
			// runtime arguments and so is never cached.
			if (instance.Production == ProductionKind.Instance || IsParameterized(instance) || instance.Lifetime != lifetime)
			{
				continue;
			}

			string modifier = instance.IsReferenceType ? "private volatile " : "private ";
			Indent(builder, depth).Append(modifier).Append(instance.ImplementationType)
				.Append("? ").Append(names.Field(i)).AppendLine(";");
		}
	}

	private static void EmitDisposedGuard(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("if (__disposed)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("throw new global::System.ObjectDisposedException(GetType().FullName);");
		Indent(builder, depth).AppendLine("}");
	}

	private static void EmitResolutionApi(StringBuilder builder, int depth, InstanceModel[] instances, Names names, bool isScope, string containerTypeName)
	{
		List<DispatchEntry> entries = BuildDispatchEntries(instances, names);

		if (entries.Count > 0 && !isScope)
		{
			EmitDispatchTable(builder, depth, entries);
			builder.AppendLine();
		}

		Indent(builder, depth).AppendLine("public object Resolve(global::System.Type serviceType)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("if (TryResolve(serviceType, out object? instance))");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("return instance!;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine(
			"throw new global::System.InvalidOperationException($\"No registration for type '{serviceType}' on this container.\");");
		Indent(builder, depth).AppendLine("}");
		builder.AppendLine();

		Indent(builder, depth).AppendLine("public bool TryResolve(global::System.Type serviceType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance)");
		Indent(builder, depth).AppendLine("{");
		if (entries.Count == 0)
		{
			Indent(builder, depth + 1).AppendLine("instance = null;");
			Indent(builder, depth + 1).AppendLine("return false;");
			Indent(builder, depth).AppendLine("}");
			return;
		}

		string table = isScope ? containerTypeName + ".__dispatch" : "__dispatch";
		Indent(builder, depth + 1).Append("if (").Append(table).AppendLine(".TryGetValue(serviceType, out int __case))");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("switch (__case)");
		Indent(builder, depth + 2).AppendLine("{");
		for (int i = 0; i < entries.Count; i++)
		{
			Indent(builder, depth + 3).Append("case ").Append(i).Append(": instance = ")
				.Append(entries[i].Value).AppendLine("; return true;");
		}

		Indent(builder, depth + 2).AppendLine("}");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("instance = null;");
		Indent(builder, depth + 1).AppendLine("return false;");
		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     The ordered dispatch cases for an owner: each registered service type mapped to its resolver
	///     call, plus the relationship types <c>Func&lt;T&gt;</c> and <c>Lazy&lt;T&gt;</c> over it (a fresh
	///     factory/lazy bound to this owner's resolver). The order is identical on the container and its
	///     scope, so a single static table built on the container is valid for both.
	/// </summary>
	private static List<DispatchEntry> BuildDispatchEntries(InstanceModel[] instances, Names names)
	{
		List<DispatchEntry> entries = new();
		HashSet<string> seen = new(StringComparer.Ordinal);

		// Explicit service registrations first, so a directly registered relationship type (e.g. a
		// registered Lazy<T>) wins the dispatch slot over the synthetic relationship entry below. Service
		// types are unique across instances (registrations are coalesced), so each is added exactly once.
		// Seeding 'seen' here lets the synthetic pass skip any key an explicit registration already claimed.
		for (int i = 0; i < instances.Length; i++)
		{
			string resolver = names.Resolver(i);
			string[] argTypes = ArgTypes(instances[i]);
			foreach (string service in instances[i].ServiceTypes.AsArray())
			{
				if (argTypes.Length > 0)
				{
					// A parameterized service cannot be built without its runtime arguments, so its bare
					// service type is not dispatchable; it is reachable only through its Func<TArg…, T> factory.
					string parameterizedFunc = $"global::System.Func<{string.Join(", ", argTypes)}, {service}>";
					seen.Add(parameterizedFunc);
					entries.Add(new DispatchEntry(parameterizedFunc, FuncFactory(argTypes, service, resolver)));
					continue;
				}

				seen.Add(service);
				entries.Add(new DispatchEntry(service, resolver + "()"));
			}
		}

		// Synthetic Func<T>/Lazy<T> over each service, skipping any key an explicit registration already
		// claimed so the static dispatch table never contains a duplicate key (which would otherwise throw
		// from the dictionary initializer at runtime). A parameterized service is skipped: its only entry is
		// the Func<TArg…, T> added above.
		for (int i = 0; i < instances.Length; i++)
		{
			if (IsParameterized(instances[i]))
			{
				continue;
			}

			string resolver = names.Resolver(i);
			foreach (string service in instances[i].ServiceTypes.AsArray())
			{
				string func = $"global::System.Func<{service}>";
				if (seen.Add(func))
				{
					entries.Add(new DispatchEntry(func, $"new global::System.Func<{service}>(() => {resolver}())"));
				}

				string lazy = $"global::System.Lazy<{service}>";
				if (seen.Add(lazy))
				{
					entries.Add(new DispatchEntry(lazy, $"new global::System.Lazy<{service}>(() => {resolver}())"));
				}
			}
		}

		return entries;
	}

	/// <summary>
	///     Emits the static <c>__dispatch</c> table mapping each service type to its case number. It is
	///     <c>static</c> so it is built once per container type, and emitted only on the container; the nested
	///     Scope reuses it through the container type.
	/// </summary>
	private static void EmitDispatchTable(StringBuilder builder, int depth, List<DispatchEntry> entries)
	{
		Indent(builder, depth).AppendLine(
			"private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> __dispatch = new global::System.Collections.Generic.Dictionary<global::System.Type, int>");
		Indent(builder, depth).AppendLine("{");
		for (int i = 0; i < entries.Count; i++)
		{
			Indent(builder, depth + 1).Append("{ typeof(").Append(entries[i].Type).Append("), ").Append(i).AppendLine(" },");
		}

		Indent(builder, depth).AppendLine("};");
	}

	/// <summary>
	///     Emits a resolver on the base <c>Scope</c>. A parameterized service (with <c>[Arg]</c> parameters)
	///     takes those runtime arguments and is built fresh per call (regardless of its declared lifetime),
	///     so it lives here as a <c>protected</c> method the RootScope can also call. Otherwise
	///     singleton-owned services (singletons and pre-built Instances) become a <c>protected virtual</c>
	///     delegator to <c>__container.Root</c> (overridden by the RootScope); scoped services cache on the
	///     scope; transients construct fresh.
	/// </summary>
	private static void EmitScopeResolver(StringBuilder builder, int depth, int index, InstanceModel instance, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		string type = instance.ImplementationType;
		string resolver = names.Resolver(index);

		if (IsParameterized(instance))
		{
			string[] argTypes = ArgTypes(instance);
			string signature = string.Join(", ", argTypes.Select((t, i) => $"{t} a{i}"));
			string parameterizedConstruction = EmitConstruction(instance, instances, names, serviceToIndex, false);
			// Reachable from the RootScope (a singleton's Func<TArg…, T> binds it there), so it is protected.
			EmitFreshResolver(builder, depth, "protected", type, resolver, signature, parameterizedConstruction, instance.IsDisposable);
			return;
		}

		if (instance.Lifetime == Lifetime.Singleton || instance.Production == ProductionKind.Instance)
		{
			Indent(builder, depth).Append("protected virtual ").Append(type).Append(' ').Append(resolver).AppendLine("()");
			Indent(builder, depth).AppendLine("{");
			EmitDisposedGuard(builder, depth + 1);
			Indent(builder, depth + 1).Append("return __container.Root.").Append(resolver).AppendLine("();");
			Indent(builder, depth).AppendLine("}");
			return;
		}

		string construction = EmitConstruction(instance, instances, names, serviceToIndex, false);

		if (instance.Lifetime == Lifetime.Transient)
		{
			EmitFreshResolver(builder, depth, "private", type, resolver, string.Empty, construction, instance.IsDisposable);
			return;
		}

		EmitCachingResolver(builder, depth, new CachingResolver("private", type, resolver, names.Field(index), construction, instance.IsDisposable, "// Scoped: one instance per scope."));
	}

	/// <summary>
	///     Emits a resolver that constructs a fresh instance on every call (a transient, or a parameterized
	///     service that also takes the runtime arguments named in <paramref name="signature" />). A
	///     disposable instance is registered for teardown on the owner under the lock, re-checking
	///     <c>__disposed</c> so one built during a concurrent dispose is disposed here rather than leaked.
	/// </summary>
	private static void EmitFreshResolver(StringBuilder builder, int depth, string modifiers, string type, string resolver, string signature, string construction, bool disposable)
	{
		Indent(builder, depth).Append(modifiers).Append(' ').Append(type).Append(' ').Append(resolver)
			.Append('(').Append(signature).AppendLine(")");
		Indent(builder, depth).AppendLine("{");
		EmitDisposedGuard(builder, depth + 1);
		if (disposable)
		{
			Indent(builder, depth + 1).Append(type).Append(" created = ").Append(construction).AppendLine(";");
			Indent(builder, depth + 1).AppendLine("lock (this)");
			Indent(builder, depth + 1).AppendLine("{");
			Indent(builder, depth + 2).AppendLine("if (__disposed)");
			Indent(builder, depth + 2).AppendLine("{");
			Indent(builder, depth + 3).AppendLine("((global::System.IDisposable)created).Dispose();");
			Indent(builder, depth + 3).AppendLine("throw new global::System.ObjectDisposedException(GetType().FullName);");
			Indent(builder, depth + 2).AppendLine("}");
			builder.AppendLine();
			Indent(builder, depth + 2).AppendLine("(__disposables ??= new global::System.Collections.Generic.List<object>()).Add(created);");
			Indent(builder, depth + 1).AppendLine("}");
			builder.AppendLine();
			Indent(builder, depth + 1).AppendLine("return created;");
		}
		else
		{
			Indent(builder, depth + 1).Append("return ").Append(construction).AppendLine(";");
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits a singleton resolver on the <c>RootScope</c> as a <c>protected override</c>: a pre-built
	///     Instance returns the container member directly (an instance member through <c>__container</c>, a
	///     static one by simple name); a constructed/factory singleton is cached once under the lock.
	/// </summary>
	private static void EmitRootResolver(StringBuilder builder, int depth, int index, InstanceModel instance, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex)
	{
		string type = instance.ImplementationType;
		string resolver = names.Resolver(index);

		if (instance.Production == ProductionKind.Instance)
		{
			string receiver = instance.ProductionMemberIsStatic ? string.Empty : "__container.";
			Indent(builder, depth).Append("protected override ").Append(type).Append(' ').Append(resolver).AppendLine("()");
			Indent(builder, depth).AppendLine("{");
			EmitDisposedGuard(builder, depth + 1);
			Indent(builder, depth + 1).Append("return ").Append(receiver).Append(instance.ProductionMember).AppendLine(";");
			Indent(builder, depth).AppendLine("}");
			return;
		}

		string construction = EmitConstruction(instance, instances, names, serviceToIndex, true);
		EmitCachingResolver(builder, depth, new CachingResolver("protected override", type, resolver, names.Field(index), construction, instance.IsDisposable, null));
	}

	/// <summary>
	///     Emits a lock-free-read, lock-on-write cached resolver: return the cached field if set, otherwise
	///     construct once under <c>lock (this)</c>, registering a disposable instance for teardown.
	/// </summary>
	private static void EmitCachingResolver(StringBuilder builder, int depth, in CachingResolver resolver)
	{
		if (resolver.Comment is not null)
		{
			Indent(builder, depth).AppendLine(resolver.Comment);
		}

		Indent(builder, depth).Append(resolver.Modifiers).Append(' ').Append(resolver.Type).Append(' ').Append(resolver.Method).AppendLine("()");
		Indent(builder, depth).AppendLine("{");
		EmitDisposedGuard(builder, depth + 1);
		Indent(builder, depth + 1).Append("if (").Append(resolver.Field).AppendLine(" is not null)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).Append("return ").Append(resolver.Field).AppendLine(";");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("lock (this)");
		Indent(builder, depth + 1).AppendLine("{");
		EmitDisposedGuard(builder, depth + 2);
		Indent(builder, depth + 2).Append("if (").Append(resolver.Field).AppendLine(" is null)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).Append(resolver.Field).Append(" = ").Append(resolver.Construction).AppendLine(";");
		if (resolver.Disposable)
		{
			Indent(builder, depth + 3).Append("(__disposables ??= new global::System.Collections.Generic.List<object>()).Add(").Append(resolver.Field).AppendLine(");");
		}

		Indent(builder, depth + 2).AppendLine("}");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).Append("return ").Append(resolver.Field).AppendLine(";");
		Indent(builder, depth).AppendLine("}");
	}

	private static string EmitConstruction(InstanceModel instance, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex, bool ownerIsRoot)
	{
		ParameterModel[] parameters = instance.ConstructorParameters.AsArray();
		StringBuilder arguments = new();
		int argIndex = 0;
		for (int p = 0; p < parameters.Length; p++)
		{
			if (p > 0)
			{
				arguments.Append(", ");
			}

			// Runtime arguments are passed in as a0, a1, … by the parameterized resolver; the rest resolve
			// from the graph.
			arguments.Append(parameters[p].Kind == DependencyKind.Arg
				? "a" + argIndex++
				: ResolveExpression(parameters[p], instances, names, serviceToIndex, ownerIsRoot));
		}

		if (instance.Production == ProductionKind.Factory)
		{
			// Both Scope and RootScope are nested in the container, so a static factory method is in scope
			// by simple name; an instance method is reached through the container.
			string receiver = instance.ProductionMemberIsStatic ? string.Empty : "__container.";
			return $"{receiver}{instance.ProductionMember}({arguments})";
		}

		return $"new {instance.ImplementationType}({arguments})";
	}

	/// <summary>
	///     The expression that supplies a single constructor argument. The target resolves through the
	///     owner's own resolver, except when a singleton being built on the root captures a non-singleton
	///     (only ever through a relationship): the root's scoped/transient resolvers are private to the base,
	///     so it routes that target through the root's generic <c>Resolve&lt;T&gt;</c> entry. A relationship
	///     type wraps the target in a deferred <c>Func&lt;T&gt;</c> / <c>Lazy&lt;T&gt;</c>.
	/// </summary>
	private static string ResolveExpression(ParameterModel parameter, InstanceModel[] instances, Names names, Dictionary<string, int> serviceToIndex, bool ownerIsRoot)
	{
		int targetIndex = serviceToIndex[parameter.ServiceType];
		string resolver = names.Resolver(targetIndex);
		InstanceModel target = instances[targetIndex];

		string[] funcArgTypes = parameter.FuncArgTypes.AsArray();
		if (parameter.Kind == DependencyKind.Func && funcArgTypes.Length > 0)
		{
			// A Func<TArg…, T> over a parameterized service binds the owner's parameterized resolver, which
			// takes the runtime arguments and is never cached - so the root routing below does not apply (the
			// protected resolver is reachable from the RootScope directly).
			return FuncFactory(funcArgTypes, parameter.ServiceType, resolver);
		}

		bool rootOwned = target.Lifetime == Lifetime.Singleton || target.Production == ProductionKind.Instance;
		string value = ownerIsRoot && !rootOwned ? $"Resolve<{parameter.ServiceType}>()" : $"{resolver}()";

		return parameter.Kind switch
		{
			DependencyKind.Func => $"new global::System.Func<{parameter.ServiceType}>(() => {value})",
			DependencyKind.Lazy => $"new global::System.Lazy<{parameter.ServiceType}>(() => {value})",
			_ => value,
		};
	}

	/// <summary>
	///     A <c>new Func&lt;TArg…, T&gt;((a0, …) =&gt; resolver(a0, …))</c> expression that forwards the
	///     runtime arguments to a parameterized service's resolver. With no argument types this is the plain
	///     deferred <c>Func&lt;T&gt;</c>.
	/// </summary>
	private static string FuncFactory(string[] argTypes, string service, string resolver)
	{
		string generics = argTypes.Length == 0 ? service : string.Join(", ", argTypes) + ", " + service;
		string lambdaArgs = string.Join(", ", argTypes.Select((_, i) => "a" + i));
		return $"new global::System.Func<{generics}>(({lambdaArgs}) => {resolver}({lambdaArgs}))";
	}

	private static bool IsParameterized(InstanceModel instance) => ArgTypes(instance).Length > 0;

	/// <summary>
	///     The ordered runtime-argument types of an instance: the service types of its <c>[Arg]</c>-marked
	///     constructor parameters, in declaration order.
	/// </summary>
	private static string[] ArgTypes(InstanceModel instance)
		=> instance.ConstructorParameters.AsArray()
			.Where(p => p.Kind == DependencyKind.Arg)
			.Select(p => p.ServiceType)
			.ToArray();

	private static void EmitDispose(StringBuilder builder, int depth)
	{
		Indent(builder, depth).AppendLine("public void Dispose()");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("global::System.Collections.Generic.List<object>? __toDispose;");
		Indent(builder, depth + 1).AppendLine("lock (this)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("if (__disposed)");
		Indent(builder, depth + 2).AppendLine("{");
		Indent(builder, depth + 3).AppendLine("return;");
		Indent(builder, depth + 2).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 2).AppendLine("__disposed = true;");
		// Hand off the list rather than copying it: nulling the field releases ownership without allocating.
		Indent(builder, depth + 2).AppendLine("__toDispose = __disposables;");
		Indent(builder, depth + 2).AppendLine("__disposables = null;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		// Dispose outside the lock so user code does not run under the lock.
		EmitDrainDisposables(builder, depth + 1);
		Indent(builder, depth).AppendLine("}");
	}

	private static void EmitErrorBody(StringBuilder builder, int depth, string typeName)
	{
		string message =
			$"\"Awaiten: container '{typeName}' has registration errors; see the build diagnostics (AWT1xx).\"";
		Indent(builder, depth).Append(
				"public object Resolve(global::System.Type serviceType) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth).AppendLine("public bool TryResolve(global::System.Type serviceType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("instance = null;");
		Indent(builder, depth + 1).AppendLine("return false;");
		Indent(builder, depth).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth).Append(
				"public global::Awaiten.IAwaitenScope CreateScope() => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth).AppendLine("public void Dispose() { }");
	}

	private static StringBuilder Indent(StringBuilder builder, int depth)
	{
		for (int i = 0; i < depth; i++)
		{
			builder.Append('\t');
		}

		return builder;
	}

	/// <summary>
	///     The inputs to <see cref="EmitCachingResolver" />: the method <see cref="Modifiers" /> and return
	///     <see cref="Type" />, the resolver <see cref="Method" /> name and backing <see cref="Field" />, the
	///     <see cref="Construction" /> expression, whether the instance <see cref="Disposable">needs disposal</see>,
	///     and an optional leading <see cref="Comment" />.
	/// </summary>
	private readonly struct CachingResolver(string modifiers, string type, string method, string field, string construction, bool disposable, string? comment)
	{
		public string Modifiers { get; } = modifiers;

		public string Type { get; } = type;

		public string Method { get; } = method;

		public string Field { get; } = field;

		public string Construction { get; } = construction;

		public bool Disposable { get; } = disposable;

		public string? Comment { get; } = comment;
	}

	/// <summary>
	///     A single dispatch case: the service <see cref="Type" /> requested and the <see cref="Value" />
	///     assigned to <c>instance</c> (the resolver call).
	/// </summary>
	private readonly struct DispatchEntry(string type, string value)
	{
		public string Type { get; } = type;

		public string Value { get; } = value;
	}

	/// <summary>
	///     Assigns each instance a readable resolver method name (<c>ResolveGreeter</c>) and cache
	///     field name (<c>_greeter</c>) derived from the implementation's simple type name, appending a
	///     numeric suffix only when two implementations would otherwise collide (case-insensitively).
	/// </summary>
	private sealed class Names
	{
		private readonly string[] _fields;
		private readonly string[] _resolvers;

		private Names(string[] resolvers, string[] fields)
		{
			_resolvers = resolvers;
			_fields = fields;
		}

		public string Resolver(int index) => _resolvers[index];

		public string Field(int index) => _fields[index];

		public static Names Build(InstanceModel[] instances)
		{
			string[] resolvers = new string[instances.Length];
			string[] fields = new string[instances.Length];
			HashSet<string> used = new(StringComparer.OrdinalIgnoreCase);

			for (int i = 0; i < instances.Length; i++)
			{
				string baseName = Sanitize(instances[i].Name);
				string name = baseName;
				int suffix = 2;
				while (!used.Add(name))
				{
					name = baseName + suffix;
					suffix++;
				}

				resolvers[i] = "Resolve" + name;
				fields[i] = "_" + char.ToLowerInvariant(name[0]) + name.Substring(1);
			}

			return new Names(resolvers, fields);
		}

		private static string Sanitize(string name)
		{
			if (string.IsNullOrEmpty(name))
			{
				return "Service";
			}

			StringBuilder builder = new(name.Length);
			foreach (char c in name.Where(c => char.IsLetterOrDigit(c) || c == '_'))
			{
				builder.Append(c);
			}

			if (builder.Length == 0 || (!char.IsLetter(builder[0]) && builder[0] != '_'))
			{
				builder.Insert(0, '_');
			}

			return builder.ToString();
		}
	}
}
