using System.Text;

namespace Awaiten.SourceGenerators;

/// <summary>
///     Emits the <c>partial class</c> implementation of a container from its
///     <see cref="ContainerModel" />, re-opening any enclosing types as <c>partial</c> so the
///     container can be a nested type.
/// </summary>
internal static class Emitter
{
	public static string Emit(ContainerModel model)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();

		int depth = 0;
		bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
		if (hasNamespace)
		{
			builder.Append("namespace ").AppendLine(model.Namespace);
			builder.AppendLine("{");
			depth++;
		}

		foreach (TypeDeclaration containing in model.ContainingTypes.AsArray())
		{
			Indent(builder, depth).Append("partial ").Append(containing.Keyword).Append(' ').AppendLine(containing.Name);
			Indent(builder, depth).AppendLine("{");
			depth++;
		}

		Indent(builder, depth).Append("partial class ").Append(model.TypeName)
			.AppendLine(" : global::Awaiten.IAwaitenContainer");
		Indent(builder, depth).AppendLine("{");

		if (model.HasErrors)
		{
			EmitErrorBody(builder, depth + 1, model.TypeName);
		}
		else
		{
			EmitBody(builder, depth + 1, model);
		}

		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < model.ContainingTypes.Count; i++)
		{
			depth--;
			Indent(builder, depth).AppendLine("}");
		}

		if (hasNamespace)
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	private static void EmitBody(StringBuilder builder, int depth, ContainerModel model)
	{
		RegistrationModel[] registrations = model.Registrations.AsArray();

		// service type -> registration index, for wiring constructor parameters.
		Dictionary<string, int> serviceToIndex = new(StringComparer.Ordinal);
		for (int i = 0; i < registrations.Length; i++)
		{
			serviceToIndex[registrations[i].ServiceType] = i;
		}

		// Singleton/Scoped backing fields.
		for (int i = 0; i < registrations.Length; i++)
		{
			RegistrationModel registration = registrations[i];
			if (registration.Lifetime != Lifetime.Transient)
			{
				Indent(builder, depth).Append("private ").Append(registration.ImplementationType)
					.Append("? __instance_").Append(i).AppendLine(";");
			}
		}

		if (registrations.Length > 0)
		{
			builder.AppendLine();
		}

		Indent(builder, depth).AppendLine("public T Get<T>() => (T)Resolve(typeof(T));");
		builder.AppendLine();
		Indent(builder, depth).AppendLine("public object Resolve(global::System.Type serviceType)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("if (TryResolve(serviceType, out object? instance))");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("return instance!;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine(
			"throw new global::System.InvalidOperationException($\"No registration for type '{serviceType}' on this container.\");");
		Indent(builder, depth).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth).AppendLine("public bool TryResolve(global::System.Type serviceType, out object? instance)");
		Indent(builder, depth).AppendLine("{");
		for (int i = 0; i < registrations.Length; i++)
		{
			Indent(builder, depth + 1).Append("if (serviceType == typeof(").Append(registrations[i].ServiceType)
				.Append(")) { instance = Resolve_").Append(i).AppendLine("(); return true; }");
		}

		Indent(builder, depth + 1).AppendLine("instance = null;");
		Indent(builder, depth + 1).AppendLine("return false;");
		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < registrations.Length; i++)
		{
			RegistrationModel registration = registrations[i];
			builder.AppendLine();
			if (registration.Lifetime == Lifetime.Scoped)
			{
				Indent(builder, depth).AppendLine("// TODO Phase 2: scoped lifetime is resolved as singleton for now.");
			}

			string construction = EmitConstruction(registration, serviceToIndex);
			Indent(builder, depth).Append("private ").Append(registration.ImplementationType)
				.Append(" Resolve_").Append(i).Append("() => ");
			if (registration.Lifetime == Lifetime.Transient)
			{
				builder.Append(construction).AppendLine(";");
			}
			else
			{
				builder.Append("__instance_").Append(i).Append(" ??= ").Append(construction).AppendLine(";");
			}
		}
	}

	private static string EmitConstruction(RegistrationModel registration, Dictionary<string, int> serviceToIndex)
	{
		string[] parameters = registration.ConstructorParameterServiceTypes.AsArray();
		StringBuilder arguments = new();
		for (int p = 0; p < parameters.Length; p++)
		{
			if (p > 0)
			{
				arguments.Append(", ");
			}

			arguments.Append("Resolve_").Append(serviceToIndex[parameters[p]]).Append("()");
		}

		return $"new {registration.ImplementationType}({arguments})";
	}

	private static void EmitErrorBody(StringBuilder builder, int depth, string typeName)
	{
		string message =
			$"\"Awaiten: container '{typeName}' has registration errors; see the build diagnostics (AWT1xx).\"";
		Indent(builder, depth).Append("public T Get<T>() => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth).Append(
				"public object Resolve(global::System.Type serviceType) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth).AppendLine("public bool TryResolve(global::System.Type serviceType, out object? instance)");
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).AppendLine("instance = null;");
		Indent(builder, depth + 1).AppendLine("return false;");
		Indent(builder, depth).AppendLine("}");
	}

	private static StringBuilder Indent(StringBuilder builder, int depth)
	{
		for (int i = 0; i < depth; i++)
		{
			builder.Append('\t');
		}

		return builder;
	}
}
