using System.Text;
using Awaiten.SourceGenerators.Entities;

namespace Awaiten.SourceGenerators;

/// <summary>
///     Emits a container's members from its <see cref="ContainerModel" />: a base <c>Scope</c> holding the
///     resolution logic and a sealed <c>Root</c> subclass owning the thread-safe singletons. Enclosing types
///     are re-opened as <c>partial</c> so the container can be nested.
/// </summary>
internal static partial class Sources
{
	public static string Emit(ContainerModel model)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();

		int depth = 0;
		bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
		if (hasNamespace)
		{
			builder.Append("namespace ").AppendLine(model.Namespace);
			builder.AppendLine("{");
			depth++;
		}

		foreach (TypeDeclaration containing in model.ContainingTypes.AsArray())
		{
			Indent(builder, depth).Append("partial ").Append(containing.Keyword).Append(' ').AppendLine(containing.Name);
			Indent(builder, depth).AppendLine("{");
			depth++;
		}

		Indent(builder, depth).Append("static partial class ").AppendLine(model.TypeName);
		Indent(builder, depth).AppendLine("{");

		if (model.HasErrors)
		{
			EmitErrorBody(builder, depth + 1, model.TypeName, model.HasAsyncDisposable);
		}
		else
		{
			Names names = Names.Build(model.Instances.AsArray(), model.Collections.AsArray(), model.KeyedCollections.AsArray(), model.SyncResolveAfterInit);
			Dictionary<ServiceKey, int> serviceToIndex = BuildServiceMap(model);
			EmitContainerBody(builder, depth + 1, model, names, serviceToIndex);
		}

		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < model.ContainingTypes.Count; i++)
		{
			depth--;
			Indent(builder, depth).AppendLine("}");
		}

		if (hasNamespace)
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	/// <summary>
	///     The context shared by the resolver emitters: the instance list, name table, service→index dispatch
	///     map, and whether the container emits the <c>IAsyncDisposable</c> surface.
	/// </summary>
	private readonly record struct EmitContext(
		InstanceModel[] Instances,
		Names Names,
		Dictionary<ServiceKey, int> ServiceToIndex,
		bool AsyncDisposal);

	/// <summary>
	///     The three region buffers a resolution-API emitter routes into: its public <see cref="Members" />, the
	///     dispatch-table <see cref="Fields" /> and the private <see cref="Helpers" />.
	/// </summary>
	private readonly record struct ApiRegions(StringBuilder Members, StringBuilder Fields, StringBuilder Helpers);

	private static void EmitContainerBody(StringBuilder builder, int depth, ContainerModel model, Names names, Dictionary<ServiceKey, int> serviceToIndex)
	{
		EmitContext context = new(model.Instances.AsArray(), names, serviceToIndex, model.HasAsyncDisposable);

		// The base Scope holds the dispatch table and scoped/transient logic and delegates singletons to the
		// root; the sealed Root owns the singletons and is the usable instance (new MyContainer.Root()).
		EmitRootClass(builder, depth, context, model.SyncResolveAfterInit);
		builder.AppendLine();
		EmitScopeBaseClass(builder, depth, context, model.Strict, model.SyncResolveAfterInit, model.VarianceCandidates.AsArray());

		// The __AsyncArray<T> backing type for IAsyncEnumerable<T> collections is emitted only when the async
		// collection materialization is actually used.
		if (NeedsAsyncArrayHelper(context.Instances, names, serviceToIndex))
		{
			builder.AppendLine();
			EmitAsyncArrayHelper(builder, depth);
		}
	}

	private static bool IsRootOwned(InstanceModel instance)
		=> !instance.IsRequestingTypeFactory
		   && (instance.Lifetime == Lifetime.Singleton || instance.Production == ProductionKind.Instance);

	/// <summary>
	///     Whether synchronous resolution members are emitted for an instance: always for a non-tainted service,
	///     and for an async-tainted one only in pragmatic mode (SyncResolveAfterInit). In the strict default an
	///     async-tainted service is reachable only through ResolveAsync.
	/// </summary>
	private static bool EmitsSync(InstanceModel instance, bool syncResolveAfterInit)
		=> !instance.IsAsyncTainted || syncResolveAfterInit;

	/// <summary>
	///     Emits the base <c>Scope</c>: the home of resolution logic. It caches scoped instances, constructs
	///     transients, and resolves singletons through virtual delegators the <c>Root</c> overrides. Child scopes
	///     are instances of this type.
	/// </summary>
	private static void EmitScopeBaseClass(StringBuilder builder, int depth, EmitContext context, bool strict, bool syncResolveAfterInit, string[] varianceCandidates)
	{
		InstanceModel[] instances = context.Instances;
		Names names = context.Names;
		Dictionary<ServiceKey, int> serviceToIndex = context.ServiceToIndex;
		bool asyncDisposal = context.AsyncDisposal;

		AppendXmlSummary(builder, depth,
			"A resolution scope: caches scoped services and disposes the instances it created.");
		Indent(builder, depth).Append("public class Scope : global::Awaiten.IAwaitenScope, global::Awaiten.IExternalResolverHost");
		if (asyncDisposal)
		{
			// IAsyncDisposable is implemented on the concrete Scope, not the IAwaitenScope interface (which would
			// break every hand-implementer). Emitted only when the compilation can see the type.
			builder.Append(", global::System.IAsyncDisposable");
		}

		EmitGenericResolverBases(builder, instances, strict, syncResolveAfterInit);
		builder.AppendLine();
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		// Members are collected into per-region buffers and assembled into #region groups below. Emit order within
		// a buffer, not call order, decides layout, so emitters run in whatever order threads state most simply.
		StringBuilder fields = new();
		StringBuilder members = new();
		StringBuilder typed = new();
		StringBuilder resolvers = new();
		StringBuilder helpers = new();

		// The static dispatch table lives on the Scope, built once for the whole container. A root-withheld entry
		// also appears in the __withheld table and carries the RootWithheld slot flag (consulted only on the Root),
		// so a child scope resolves it while the Root withholds it.
		List<DispatchEntry> entries = BuildDispatchEntries(instances, names, serviceToIndex, strict, syncResolveAfterInit);
		List<DispatchEntry> rootWithheld = Withheld(entries);
		// The __withheld guidance table merges the root-withheld disposable services and the async-tainted services
		// excluded from synchronous resolution, so Resolve surfaces a targeted message instead of the generic "no
		// registration". Only the former needs the RootWithheld slot flag, which rides on the dispatch entries.
		List<(string Type, string Guidance)> withheldTypes = WithheldTypes(rootWithheld, instances, names, serviceToIndex, syncResolveAfterInit);

		// Fields region. The dispatch table's static fields and static constructor land here; its slot type,
		// distributor and __R forwarders go to helpers. An open-addressed table keyed by Type identity hash grows
		// in data, never in a single method's IL, so it never exceeds the JIT's optimization guards.
		if (entries.Count > 0)
		{
			EmitBucketDispatch(fields, helpers, body, entries);
		}

		if (withheldTypes.Count > 0)
		{
			Separate(fields);
			EmitWithheldTable(fields, body, withheldTypes);
		}

		// The root scope this scope resolves singletons through: holding it directly devirtualizes the singleton
		// call. Synchronization is on a private gate object, not the owner, so consumer code (lock (scope)) cannot
		// interfere with resolution and disposal. The disposables list is lazy. All protected so the Root's
		// singleton overrides share the same gate and list.
		Separate(fields);
		Indent(fields, body).AppendLine("protected readonly Root __root;");
		Indent(fields, body).AppendLine("protected readonly object __gate = new object();");
		Indent(fields, body).AppendLine("protected volatile bool __disposed;");
		Indent(fields, body).AppendLine("protected global::System.Collections.Generic.List<object>? __disposables;");
		// The queued OnRelease actions, run (reverse creation order) ahead of __disposables on teardown. Emitted
		// only when some registration names an OnRelease hook, so containers without one carry no extra field.
		if (HasReleaseHooks(instances))
		{
			Indent(fields, body).AppendLine("protected global::System.Collections.Generic.List<global::System.Action>? __releases;");
		}

		if (NeedsWiringSupport(instances))
		{
			// The nesting depth of the wiring episode in progress on this owner (touched only under __gate). The
			// outermost frame commits every wiring flag (or rolls back) once, so a nested participant is never
			// flagged wired while an outer participant that references it is still half-wired.
			Indent(fields, body).AppendLine("protected int __wiring;");
		}

		EmitCacheFields(fields, body, instances, names, Lifetime.Scoped);

		// The external resolver this scope routes its [ImportService<T>] / [ImportServices] dependencies through. A
		// host wires each scope; a child without its own falls back to the root's in __ResolveExternal. The
		// explicit IExternalResolverHost.ExternalResolver property lands in the members region.
		Separate(fields);
		Indent(fields, body).AppendLine("private global::Awaiten.IExternalResolver? __externalResolver;");

		// Members region: constructors, public surface and non-typed explicit interface implementations. The root
		// is its own __root (the parameterless ctor is only reached through Root's base call); child scopes get the
		// shared root. The child ctor is private so a scope is only created through CreateScope().
		Indent(members, body).AppendLine("private protected Scope()");
		Indent(members, body).AppendLine("{");
		Indent(members, body + 1).AppendLine("__root = (Root)this;");
		Indent(members, body).AppendLine("}");
		Separate(members);
		Indent(members, body).AppendLine("private Scope(Root root)");
		Indent(members, body).AppendLine("{");
		Indent(members, body + 1).AppendLine("__root = root;");
		Indent(members, body).AppendLine("}");

		Separate(members);
		Indent(members, body).AppendLine("global::Awaiten.IExternalResolver? global::Awaiten.IExternalResolverHost.ExternalResolver");
		Indent(members, body).AppendLine("{");
		Indent(members, body + 1).AppendLine("get => __externalResolver;");
		Indent(members, body + 1).AppendLine("set => __externalResolver = value;");
		Indent(members, body).AppendLine("}");

		ApiRegions regions = new(members, fields, helpers);
		DispatchShape dispatch = EmitResolutionApi(regions, body, context, strict, syncResolveAfterInit, varianceCandidates);
		Separate(members);
		EmitGenericResolveMethod(members, body);
		// The asynchronous surface: ResolveAsync(Type) on every owner, plus CreateScopeAsync. The Root's
		// InitializeAsync and per-singleton async resolvers are emitted on the Root.
		bool asObjectEmitted = EmitAsyncResolutionApi(regions, body, instances, names, serviceToIndex, strict, syncResolveAfterInit);
		// The keyed resolution surface (Resolve/TryResolve/ResolveAsync over object? key), sharing the __AsObject
		// helper with the async dispatch above.
		bool hasKeyedEntries = EmitKeyedResolutionApi(regions, body, context, strict, syncResolveAfterInit, asObjectEmitted);
		// The resolvability probe reads the dispatch tables both surfaces just emitted, so it comes after both.
		EmitResolvabilityApi(regions, body, dispatch, hasKeyedEntries);
		Separate(members);
		EmitCreateScopeAsync(members, body);
		// Nesting shares the same root (same singletons), so a child created from a child is no different from one
		// created from the root. A child scope's lifetime is owned by its caller; the parent does not track it.
		Separate(members);
		AppendXmlSummary(members, body,
			"Opens a child scope; the caller owns and disposes it.");
		Indent(members, body).AppendLine("public Scope CreateScope() => new Scope(__root);");
		Indent(members, body).AppendLine("global::Awaiten.IAwaitenScope global::Awaiten.IAwaitenScope.CreateScope() => CreateScope();");
		Separate(members);
		bool hasReleases = HasReleaseHooks(instances);
		EmitDispose(members, body, asyncDisposal, hasReleases);
		if (asyncDisposal)
		{
			Separate(members);
			EmitDisposeAsync(members, body, hasReleases);
		}

		// Typed-resolver region: the explicit IAwaitenResolver<T>.Resolve() fast path for each registered service.
		EmitGenericResolverImpls(typed, body, instances, names, strict, syncResolveAfterInit);

		// Resolvers region: the per-type internal static resolvers, plus one async by-type resolver per async
		// collection (whose IAsyncEnumerable<T> shape ResolveAsync serves through the async dispatch arm).
		EmitInstanceResolvers(resolvers, body, context, instances, names, syncResolveAfterInit);
		foreach ((ServiceMembers collection, string method) in AsyncByTypeCollections(names, serviceToIndex, syncResolveAfterInit))
		{
			Separate(resolvers);
			EmitAsyncCollectionResolver(resolvers, body, collection, method, names, instances);
		}

		// Helpers region: __WarmAsync, the Owned helpers, __ResolveExternal and the wiring commit/rollback pair,
		// alongside the dispatch-table helper members already routed here above.
		Separate(helpers);
		EmitScopeInitializeAsync(helpers, body, instances, names);
		if (instances.Length > 0)
		{
			Separate(helpers);
			EmitOwnedHelper(helpers, body, HasExternalDependencies(instances));
		}

		// The __ResolveExternal helper is emitted only when the container has [ImportService<T>] / [ImportServices]
		// dependencies, so a container without them carries no unused helper.
		if (HasExternalDependencies(instances))
		{
			Separate(helpers);
			EmitResolveExternal(helpers, body);
		}

		if (NeedsWiringSupport(instances))
		{
			Separate(helpers);
			EmitWiringSupport(helpers, body, instances, names, root: false);
		}

		EmitSections(builder, body,
			new MemberSection("Fields", fields),
			new MemberSection(null, members),
			new MemberSection("Explicit IAwaitenResolver<T> implementations", typed),
			new MemberSection("Resolvers", resolvers),
			new MemberSection("Helpers", helpers));

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits each instance's per-service resolvers into the Scope body: a synchronous resolver (suppressed for
	///     an async-tainted service in the strict default, delegating to the async one in pragmatic mode) and, for
	///     every async-tainted service, its async resolver.
	/// </summary>
	private static void EmitInstanceResolvers(StringBuilder builder, int depth, EmitContext context, InstanceModel[] instances, Names names, bool syncResolveAfterInit)
	{
		for (int i = 0; i < instances.Length; i++)
		{
			// Singleton-owned instances (singletons and pre-built Instances) are emitted as static resolvers on the
			// Root (see EmitRootClass); the base Scope hosts only the scoped, transient and parameterized ones.
			if (IsRootOwned(instances[i]))
			{
				continue;
			}

			if (EmitsSync(instances[i], syncResolveAfterInit))
			{
				Separate(builder);
				if (instances[i].IsAsyncTainted)
				{
					EmitDelegatingSyncResolver(builder, depth, i, instances[i], names, "Scope");
				}
				else
				{
					EmitScopeResolver(builder, depth, i, context);
				}
			}

			if (instances[i].IsAsyncTainted)
			{
				Separate(builder);
				EmitAsyncScopeResolver(builder, depth, i, context);
			}
		}
	}

	/// <summary>
	///     Whether the container needs the deferred-wiring machinery (<c>__wiring</c> counter and
	///     <c>__CommitWiring</c>/<c>__RollbackWiring</c>): some synchronously-cached instance has a deferred
	///     (<c>[Inject(Deferred = true)]</c>) member.
	/// </summary>
	private static bool NeedsWiringSupport(InstanceModel[] instances)
		=> instances.Any(instance => IsSyncCachedDeferred(instance, Lifetime.Singleton) || IsSyncCachedDeferred(instance, Lifetime.Scoped));

	/// <summary>
	///     Whether the instance is cached by a synchronous caching resolver of the given lifetime and has deferred
	///     members: exactly the instances that get a wiring flag and participate in wiring episodes.
	/// </summary>
	private static bool IsSyncCachedDeferred(InstanceModel instance, Lifetime lifetime)
		=> instance.Lifetime == lifetime
		   && instance.Production != ProductionKind.Instance
		   && !instance.IsParameterized
		   && !instance.IsAsyncTainted
		   && HasDeferredMembers(instance);

	/// <summary>
	///     Emits the wiring-episode commit/rollback pair over the owner's deferred-member instances.
	///     <c>__CommitWiring</c> flags every published instance as fully wired; <c>__RollbackWiring</c> unpublishes
	///     a failed episode's half-wired instances so the next resolve rebuilds. Virtual because a Root episode
	///     spans its inherited scoped instances and its singletons under one gate, so the override must flush both.
	/// </summary>
	private static void EmitWiringSupport(StringBuilder builder, int depth, InstanceModel[] instances, Names names, bool root)
	{
		string modifiers = root ? "private protected override" : "private protected virtual";
		Lifetime lifetime = root ? Lifetime.Singleton : Lifetime.Scoped;

		AppendXmlSummary(builder, depth,
			"Marks every published deferred-member instance as fully wired: called by the outermost frame of a",
			"successful wiring episode, so a half-wired instance is never observable through the lock-free fast",
			"path, not even transitively through an already-published peer.");
		Indent(builder, depth).Append(modifiers).AppendLine(" void __CommitWiring()");
		Indent(builder, depth).AppendLine("{");
		if (root)
		{
			Indent(builder, depth + 1).AppendLine("base.__CommitWiring();");
		}

		for (int i = 0; i < instances.Length; i++)
		{
			if (IsSyncCachedDeferred(instances[i], lifetime))
			{
				Indent(builder, depth + 1).Append("if (").Append(names.Field(i)).AppendLine(" is not null)");
				Indent(builder, depth + 1).AppendLine("{");
				Indent(builder, depth + 2).Append(names.WiredField(i)).AppendLine(" = true;");
				Indent(builder, depth + 1).AppendLine("}");
			}
		}

		Indent(builder, depth).AppendLine("}");
		builder.AppendLine();

		AppendXmlSummary(builder, depth,
			"Unpublishes every instance a failed wiring episode left half-wired (published, wiring flag still",
			"false), so the next resolve rebuilds it instead of silently returning a half-wired instance.");
		Indent(builder, depth).Append(modifiers).AppendLine(" void __RollbackWiring()");
		Indent(builder, depth).AppendLine("{");
		if (root)
		{
			Indent(builder, depth + 1).AppendLine("base.__RollbackWiring();");
		}

		for (int i = 0; i < instances.Length; i++)
		{
			if (IsSyncCachedDeferred(instances[i], lifetime))
			{
				Indent(builder, depth + 1).Append("if (!").Append(names.WiredField(i)).AppendLine(")");
				Indent(builder, depth + 1).AppendLine("{");
				Indent(builder, depth + 2).Append(names.Field(i)).AppendLine(" = null;");
				Indent(builder, depth + 1).AppendLine("}");
			}
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the <c>Root</c>: where singletons (and pre-built Instances) live, and the usable container
	///     instance (<c>new MyContainer.Root()</c>). It overrides the base's virtual singleton delegators, so a
	///     child scope delegating through <c>__root</c> lands here.
	/// </summary>
	private static void EmitRootClass(StringBuilder builder, int depth, EmitContext context, bool syncResolveAfterInit)
	{
		InstanceModel[] instances = context.Instances;
		Names names = context.Names;

		// The Root is the composition root (IAwaitenContainerMetadata, which is an IAwaitenRoot): it adds
		// InitializeAsync to warm the singletons and advertises its registrations for the MS.DI bridge. A
		// child scope is only an IAwaitenScope; it is warmed when created (CreateScopeAsync), never explicitly.
		AppendXmlSummary(builder, depth,
			"The container root: owns the singleton instances and serves as the default scope.");
		Indent(builder, depth).AppendLine("public sealed class Root : Scope, global::Awaiten.IAwaitenContainerMetadata");
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		// Region buffers assembled into #region groups below. Emit order within a buffer, not call order, decides
		// layout, so emitters run in whatever order threads members into the right buffers.
		StringBuilder fields = new();
		StringBuilder members = new();
		StringBuilder resolvers = new();
		StringBuilder helpers = new();

		// Fields region: the singleton cache fields followed by the compile-time metadata arrays (__registrations,
		// and __externalDependencies when the container has external dependencies).
		EmitCacheFields(fields, body, instances, names, Lifetime.Singleton);

		// Members region (no #region wrapper): the constructor and the IAwaitenContainerMetadata surface
		// (InitializeAsync plus the advertised registration lists).
		AppendXmlSummary(members, body,
			"Creates the container root: the usable container instance and its default scope.");
		Indent(members, body).AppendLine("public Root() : base()");
		Indent(members, body).AppendLine("{");
		EmitEagerActivation(members, body + 1, instances, names);
		Indent(members, body).AppendLine("}");
		// The Root override of InitializeAsync warms the async singletons in dependency order (the base
		// Scope warms only its async scoped services).
		Separate(members);
		EmitRootInitializeAsync(members, body, instances, names);
		// The registration metadata array (fields region) and its IAwaitenContainerMetadata.Registrations getter
		// (members region, beside InitializeAsync).
		EmitRegistrations(fields, members, body, instances, syncResolveAfterInit);
		// The external-dependency metadata: the advertised list (fields region when non-empty) and its getter
		// (members region); the getter returns an empty array when the container has no external dependencies.
		EmitExternalMetadata(fields, members, body, instances);

		// Resolvers region: the per-singleton static resolvers overriding the base Scope's delegators.
		for (int i = 0; i < instances.Length; i++)
		{
			InstanceModel instance = instances[i];
			// A parameterized service and a requesting-type factory are never cached on the root; their
			// fresh-per-call resolver lives on the base Scope. Only singleton-owned instances get a Root override.
			if (instance.IsParameterized
			    || instance.IsRequestingTypeFactory
			    || (instance.Lifetime != Lifetime.Singleton && instance.Production != ProductionKind.Instance))
			{
				continue;
			}

			// A non-async singleton gets its caching static resolver here. An async singleton in pragmatic mode gets
			// a delegating synchronous resolver that blocks on its async one; in the strict default it has no
			// synchronous resolver at all.
			if (EmitsSync(instance, syncResolveAfterInit))
			{
				Separate(resolvers);
				if (instance.IsAsyncTainted)
				{
					EmitDelegatingSyncResolver(resolvers, body, i, instance, names, "Root");
				}
				else
				{
					EmitRootResolver(resolvers, body, i, context);
				}
			}

			if (instance.IsAsyncTainted)
			{
				Separate(resolvers);
				EmitAsyncRootResolver(resolvers, body, i, context);
			}
		}

		// Helpers region. The Root's wiring commit/rollback override adds the deferred singletons to the base
		// Scope's scoped set, so an episode on the Root flushes both kinds.
		if (instances.Any(instance => IsSyncCachedDeferred(instance, Lifetime.Singleton)))
		{
			Separate(helpers);
			EmitWiringSupport(helpers, body, instances, names, root: true);
		}

		EmitSections(builder, body,
			new MemberSection("Fields", fields),
			new MemberSection(null, members),
			new MemberSection("Resolvers", resolvers),
			new MemberSection("Helpers", helpers));

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the <c>Root</c> constructor body: each <c>Eager</c> singleton is constructed at build time, in
	///     registration order, through its caching static resolver (so it is cached and a disposable one tracked).
	///     The synchronous analog of <c>InitializeAsync</c>. An async-tainted eager singleton in the strict default
	///     is AWT161 (the throwing error body is emitted instead), so the call here is always valid.
	/// </summary>
	private static void EmitEagerActivation(StringBuilder builder, int depth, InstanceModel[] instances, Names names)
	{
		for (int i = 0; i < instances.Length; i++)
		{
			if (instances[i].Eager)
			{
				Indent(builder, depth).Append(names.Resolver(i)).AppendLine("(this);");
			}
		}
	}

	/// <summary>
	///     Emits the cache fields for instances of the given lifetime (reference-type fields are volatile so the
	///     lock-free fast path cannot observe a reference before the constructor's writes are visible on weak
	///     memory models). A pre-built Instance has no field.
	/// </summary>
	private static void EmitCacheFields(StringBuilder builder, int depth, InstanceModel[] instances, Names names, Lifetime lifetime)
	{
		// The cache fields form one contiguous block, separated from any prior region content by one blank line
		// before the first field (a no-op when the buffer is empty).
		bool separated = false;
		for (int i = 0; i < instances.Length; i++)
		{
			InstanceModel instance = instances[i];
			// A pre-built Instance, a parameterized service and a requesting-type factory are never cached (each is
			// rebuilt per call).
			if (instance.Production == ProductionKind.Instance || instance.IsParameterized || instance.IsRequestingTypeFactory || instance.Lifetime != lifetime)
			{
				continue;
			}

			if (!separated)
			{
				Separate(builder);
				separated = true;
			}

			EmitCacheField(builder, depth, instance, names, i);
		}
	}

	/// <summary>
	///     Emits the single cache field of a non-skipped instance: the synchronous cache field (plus its
	///     wired-completion flag for a deferred instance), or the async memoization field for an async-tainted one.
	/// </summary>
	private static void EmitCacheField(StringBuilder builder, int depth, InstanceModel instance, Names names, int i)
	{
		// The async cache memoizes the construction-and-initialization Task so it is awaited exactly once; it is
		// volatile so the lock-free read cannot observe it before its writes are visible.
		if (instance.IsAsyncTainted)
		{
			Indent(builder, depth).Append("private volatile global::System.Threading.Tasks.Task<").Append(instance.ConstructedType)
				.Append(">? ").Append(names.AsyncField(i)).AppendLine(";");
			return;
		}

		// The synchronous cache backs synchronous resolution. An async-tainted service is never cached here: the
		// async cache above is its single home.
		string modifier = instance.IsReferenceType ? "private volatile " : "private ";
		Indent(builder, depth).Append(modifier).Append(instance.ConstructedType)
			.Append("? ").Append(names.Field(i)).AppendLine(";");

		// A deferred ([Inject(Deferred = true)]) member is wired after the field is published, so a volatile flag
		// marks when wiring completed. The lock-free fast path gates on it (not the field alone) so a concurrent
		// caller never returns a half-wired instance, while the mid-wiring re-entrant resolve sees it still false
		// and terminates the cycle through the lock. Committed by the outermost frame of the episode.
		if (HasDeferredMembers(instance))
		{
			Indent(builder, depth).Append("private volatile bool ").Append(names.WiredField(i)).AppendLine(";");
		}
	}

	private static void EmitErrorBody(StringBuilder builder, int depth, string typeName, bool asyncDisposal)
	{
		string message =
			$"\"Awaiten: container '{typeName}' has registration errors; see the build diagnostics (AWT1xx).\"";
		// The container has registration errors, so emit a throwing Root that still satisfies the shape
		// consumers depend on, keeping the build focused on the actionable AWT diagnostics rather than cascading
		// "type not found" errors. It implements IAwaitenContainerMetadata (and IAsyncDisposable when available).
		Indent(builder, depth).Append("public sealed class Root : global::Awaiten.IAwaitenContainerMetadata");
		if (asyncDisposal)
		{
			builder.Append(", global::System.IAsyncDisposable");
		}

		builder.AppendLine();
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).Append(
				"public object Resolve(global::System.Type serviceType) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public bool TryResolve(global::System.Type serviceType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("instance = null;");
		Indent(builder, depth + 2).AppendLine("return false;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public object Resolve(global::System.Type serviceType, object? key) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public bool TryResolve(global::System.Type serviceType, object? key, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("instance = null;");
		Indent(builder, depth + 2).AppendLine("return false;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::Awaiten.IAwaitenScope CreateScope() => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::System.Threading.Tasks.Task<object> ResolveAsync(global::System.Type serviceType, global::System.Threading.CancellationToken cancellationToken = default) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::System.Threading.Tasks.Task<object> ResolveAsync(global::System.Type serviceType, object? key, global::System.Threading.CancellationToken cancellationToken = default) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::System.Threading.Tasks.Task InitializeAsync(global::System.Threading.CancellationToken cancellationToken = default) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::System.Threading.Tasks.Task<global::Awaiten.IAwaitenScope> CreateScopeAsync(global::System.Threading.CancellationToken cancellationToken = default) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public void Dispose() { }");
		if (asyncDisposal)
		{
			builder.AppendLine();
			Indent(builder, depth + 1).AppendLine("public global::System.Threading.Tasks.ValueTask DisposeAsync() => default;");
		}

		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("global::System.Collections.Generic.IReadOnlyList<global::Awaiten.AwaitenRegistration> global::Awaiten.IAwaitenContainerMetadata.Registrations => global::System.Array.Empty<global::Awaiten.AwaitenRegistration>();");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("global::System.Collections.Generic.IReadOnlyList<global::Awaiten.AwaitenExternalDependency> global::Awaiten.IAwaitenContainerMetadata.ExternalDependencies => global::System.Array.Empty<global::Awaiten.AwaitenExternalDependency>();");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public bool IsResolvable(global::System.Type serviceType, object? key) => false;");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("global::Awaiten.IExternalResolver? global::Awaiten.IExternalResolverHost.ExternalResolver { get; set; }");

		Indent(builder, depth).AppendLine("}");
	}

	private static StringBuilder Indent(StringBuilder builder, int depth)
	{
		for (int i = 0; i < depth; i++)
		{
			builder.Append('\t');
		}

		return builder;
	}

	/// <summary>
	///     Appends a blank line to <paramref name="builder" /> only when it already holds content, so successive
	///     members routed into the same region buffer are separated by one blank line without a leading blank.
	/// </summary>
	private static void Separate(StringBuilder builder)
	{
		if (builder.Length > 0)
		{
			builder.AppendLine();
		}
	}

	/// <summary>
	///     A member section of a generated class: the pre-rendered <see cref="Content" /> and, when
	///     <see cref="Region" /> is set, the <c>#region</c> name to wrap it in. An empty content buffer is skipped
	///     entirely, so a section that emits nothing carries no empty region.
	/// </summary>
	private readonly record struct MemberSection(string? Region, StringBuilder Content);

	/// <summary>
	///     Writes the non-empty <paramref name="sections" /> into the class body in order, separated by a blank
	///     line, wrapping each named section in a <c>#region</c>/<c>#endregion</c> pair at <paramref name="depth" />.
	/// </summary>
	private static void EmitSections(StringBuilder builder, int depth, params MemberSection[] sections)
	{
		bool first = true;
		foreach ((string? region, StringBuilder content) in sections)
		{
			if (content.Length == 0)
			{
				continue;
			}

			if (!first)
			{
				builder.AppendLine();
			}

			first = false;
			if (region is null)
			{
				builder.Append(content);
			}
			else
			{
				Indent(builder, depth).Append("#region ").AppendLine(region);
				builder.Append(content);
				Indent(builder, depth).AppendLine("#endregion");
			}
		}
	}

	/// <summary>
	///     Appends an XML <c>///</c> summary doc comment over the following generated member, one indented
	///     line per entry in <paramref name="lines" />.
	/// </summary>
	private static void AppendXmlSummary(StringBuilder builder, int depth, params string[] lines)
	{
		Indent(builder, depth).AppendLine("/// <summary>");
		foreach (string line in lines)
		{
			Indent(builder, depth).Append("///     ").AppendLine(line);
		}

		Indent(builder, depth).AppendLine("/// </summary>");
	}

	/// <summary>
	///     A doc-comment reference to a type in the generated code: a <c>&lt;see cref="…" /&gt;</c> for a
	///     plain fully-qualified name, and an escaped <c>&lt;c&gt;…&lt;/c&gt;</c> for a constructed generic
	///     type (which is not a valid <c>cref</c> target).
	/// </summary>
	private static string XmlTypeRef(string type)
		=> type.IndexOf('<') < 0
			? $"<see cref=\"{type}\" />"
			: $"<c>{type.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")}</c>";
}
