using System.Text;
using Awaiten.SourceGenerators.Entities;

namespace Awaiten.SourceGenerators;

/// <summary>
///     Emits the generated partial of a <c>[Module]</c> that self-compiles its <c>[Scan]</c>: the module class is
///     re-opened as <c>partial</c>, carrying one <c>[GeneratedScanRegistration]</c> per match and one
///     <c>public static</c> factory method that constructs the match and returns its accessible exposure interface.
///     The factory body <c>new</c>s the (possibly <c>internal</c>) implementation - legal because this code compiles
///     in the module's own assembly - while the consumer only ever names the interface and calls the factory.
/// </summary>
internal static partial class Sources
{
	public static string EmitModule(ModuleScanModel model)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();

		int depth = 0;
		bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
		if (hasNamespace)
		{
			builder.Append("namespace ").AppendLine(model.Namespace);
			builder.AppendLine("{");
			depth++;
		}

		foreach (TypeDeclaration containing in model.ContainingTypes.AsArray())
		{
			Indent(builder, depth).Append("partial ").Append(containing.Keyword).Append(' ').AppendLine(containing.Name);
			Indent(builder, depth).AppendLine("{");
			depth++;
		}

		// The expansion marker: proof the module's [Scan] passed through the generator, emitted even when the
		// scan matched nothing, so a consuming container can tell "matched nothing" from "never expanded" and
		// report AWT154 only for the latter (a module assembly built without the Awaiten generator).
		Indent(builder, depth).AppendLine("[global::Awaiten.GeneratedScanExpansionAttribute]");

		// One [GeneratedScanRegistration] per generated factory, applied to the re-opened partial module. The
		// consuming container reads these like a container [Scan]'s matches (collection-eligible and overridable).
		foreach (ModuleFactory factory in model.Factories.AsArray())
		{
			Indent(builder, depth).Append('[').Append(RegistrationAttribute(factory)).AppendLine("]");
		}

		Indent(builder, depth).Append("static partial class ").AppendLine(model.TypeName);
		Indent(builder, depth).AppendLine("{");

		bool first = true;
		foreach (ModuleFactory factory in model.Factories.AsArray())
		{
			if (!first)
			{
				builder.AppendLine();
			}

			first = false;
			EmitModuleFactory(builder, depth + 1, factory);

			// The lifecycle-hook wrappers, emitted beside the factory: public so a cross-assembly consumer can run
			// them, but bodied inside the module so they may cast to and call its internal implementation and hook.
			if (factory.OnActivated is { } activation)
			{
				builder.AppendLine();
				EmitModuleHook(builder, depth + 1, factory, activation, release: false);
			}

			if (factory.OnRelease is { } release)
			{
				builder.AppendLine();
				EmitModuleHook(builder, depth + 1, factory, release, release: true);
			}
		}

		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < model.ContainingTypes.Count; i++)
		{
			depth--;
			Indent(builder, depth).AppendLine("}");
		}

		if (hasNamespace)
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	/// <summary>
	///     The registration attribute for one factory: the service is the accessible exposure interface the
	///     generated factory produces, and the lifetime is the one the scan declared. A consuming container reads
	///     <c>[GeneratedScanRegistration]</c> like a container <c>[Scan]</c>'s match - collection-eligible so
	///     several matches under one interface resolve as an <c>IEnumerable</c>, and overridable by an explicit
	///     registration - so a self-compiled scan behaves as close to a container scan as the assembly boundary allows.
	/// </summary>
	private static string RegistrationAttribute(ModuleFactory factory)
	{
		string skip = factory.SkipUnconstructable ? ", SkipUnconstructable = true" : string.Empty;

		// The hook wrapper names travel on the registration so a consumer runs them through the ordinary hook
		// pipeline, exactly like OnActivated/OnRelease on a container [Scan].
		string onActivated = factory.OnActivated is { } activation ? $", OnActivated = \"{activation.WrapperName}\"" : string.Empty;
		string onRelease = factory.OnRelease is { } release ? $", OnRelease = \"{release.WrapperName}\"" : string.Empty;
		return $"global::Awaiten.GeneratedScanRegistrationAttribute<{factory.ServiceType}>(\"{factory.FactoryName}\", Lifetime = global::Awaiten.AwaitenLifetime.{factory.Lifetime}{skip}{onActivated}{onRelease})";
	}

	private static void EmitModuleFactory(StringBuilder builder, int depth, ModuleFactory factory)
	{
		AppendXmlSummary(builder, depth,
			"Generated from a module [Scan]: constructs the scanned implementation and exposes it through its",
			"accessible interface, so a consuming container resolves it without naming the implementation.");

		// Parameter names are emitted verbatim-prefixed: a scanned constructor may legally name a parameter with a
		// reserved keyword ('@event'), whose symbol name carries no '@', and the prefix is harmless otherwise.
		FactoryParameter[] parameters = factory.Parameters.AsArray();
		string signature = string.Join(", ", parameters.Select(parameter => $"{parameter.Type} @{parameter.Name}"));
		string arguments = string.Join(", ", parameters.Select(parameter => $"@{parameter.Name}"));

		Indent(builder, depth)
			.Append("public static ").Append(factory.ServiceType).Append(' ').Append(factory.FactoryName)
			.Append('(').Append(signature).Append(") => new ").Append(factory.ImplementationType)
			.Append('(').Append(arguments).AppendLine(");");
	}

	/// <summary>
	///     Emits one lifecycle-hook wrapper: a <c>public static void</c> method taking the accessible exposure
	///     interface as its first parameter, casting it back to the scanned implementation (or the closed marker form
	///     of a generic hook) and forwarding it - plus the graph-resolved parameters after it - to the module's own
	///     (possibly <c>internal</c>) hook. The cast and the call compile because the wrapper body sits in the
	///     module's own assembly, while the <c>public</c> signature is all a consumer needs to run it.
	/// </summary>
	private static void EmitModuleHook(StringBuilder builder, int depth, ModuleFactory factory, ModuleHook hook, bool release)
	{
		AppendXmlSummary(builder, depth,
			$"Generated from a module [Scan]: the {(release ? "OnRelease" : "OnActivated")} lifecycle wrapper, casting the exposure",
			"interface back to the scanned implementation and forwarding to the module's own hook, so a consumer runs it without naming the internal hook.");

		FactoryParameter[] parameters = hook.Parameters.AsArray();
		string signature = string.Concat(parameters.Select(parameter => $", {parameter.Type} @{parameter.Name}"));
		string arguments = string.Concat(parameters.Select(parameter => $", @{parameter.Name}"));

		// The synthetic instance parameter carries the reserved awaiten__ prefix so it cannot collide with a mirrored
		// user hook parameter (a plain name like "instance" would be a duplicate-parameter error in the wrapper).
		Indent(builder, depth)
			.Append("public static void ").Append(hook.WrapperName)
			.Append('(').Append(factory.ServiceType).Append(" @awaiten__instance").Append(signature).Append(") => ")
			.Append(hook.Target).Append("((").Append(hook.InstanceCast).Append(")@awaiten__instance").Append(arguments).AppendLine(");");
	}
}
