using System.Text;
using Awaiten.SourceGenerators.Entities;

namespace Awaiten.SourceGenerators;

/// <summary>
///     Emits the generated partial of a <c>[Module]</c> that self-compiles its <c>[Scan]</c>: the module class is
///     re-opened as <c>partial</c>, carrying one lifetime registration attribute per match and one
///     <c>public static</c> factory method that constructs the match and returns its accessible exposure interface.
///     The factory body <c>new</c>s the (possibly <c>internal</c>) implementation - legal because this code compiles
///     in the module's own assembly - while the consumer only ever names the interface and calls the factory.
/// </summary>
internal static partial class Sources
{
	public static string EmitModule(ModuleScanModel model)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();

		int depth = 0;
		bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
		if (hasNamespace)
		{
			builder.Append("namespace ").AppendLine(model.Namespace);
			builder.AppendLine("{");
			depth++;
		}

		foreach (TypeDeclaration containing in model.ContainingTypes.AsArray())
		{
			Indent(builder, depth).Append("partial ").Append(containing.Keyword).Append(' ').AppendLine(containing.Name);
			Indent(builder, depth).AppendLine("{");
			depth++;
		}

		// One registration attribute per generated factory, applied to the re-opened partial module. The consuming
		// container reads these exactly like hand-written [Singleton<…>(Factory = …)] registrations.
		foreach (ModuleFactory factory in model.Factories.AsArray())
		{
			Indent(builder, depth).Append('[').Append(RegistrationAttribute(factory)).AppendLine("]");
		}

		Indent(builder, depth).Append("static partial class ").AppendLine(model.TypeName);
		Indent(builder, depth).AppendLine("{");

		bool first = true;
		foreach (ModuleFactory factory in model.Factories.AsArray())
		{
			if (!first)
			{
				builder.AppendLine();
			}

			first = false;
			EmitModuleFactory(builder, depth + 1, factory);
		}

		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < model.ContainingTypes.Count; i++)
		{
			depth--;
			Indent(builder, depth).AppendLine("}");
		}

		if (hasNamespace)
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	/// <summary>
	///     The single-argument lifetime registration attribute for one factory: the service is the accessible
	///     exposure interface, produced by the generated factory, and <c>Fallback.Silent</c> makes it an overridable
	///     default so a consuming container can replace it with its own registration without a conflict.
	/// </summary>
	private static string RegistrationAttribute(ModuleFactory factory)
	{
		string attribute = factory.Lifetime switch
		{
			Lifetime.Singleton => "SingletonAttribute",
			Lifetime.Scoped => "ScopedAttribute",
			_ => "TransientAttribute",
		};

		return $"global::Awaiten.{attribute}<{factory.ServiceType}>(Factory = \"{factory.FactoryName}\", Fallback = global::Awaiten.Fallback.Silent)";
	}

	private static void EmitModuleFactory(StringBuilder builder, int depth, ModuleFactory factory)
	{
		AppendXmlSummary(builder, depth,
			"Generated from a module [Scan]: constructs the scanned implementation and exposes it through its",
			"accessible interface, so a consuming container resolves it without naming the implementation.");

		FactoryParameter[] parameters = factory.Parameters.AsArray();
		string signature = string.Join(", ", parameters.Select(parameter => $"{parameter.Type} {parameter.Name}"));
		string arguments = string.Join(", ", parameters.Select(parameter => parameter.Name));

		Indent(builder, depth)
			.Append("public static ").Append(factory.ServiceType).Append(' ').Append(factory.FactoryName)
			.Append('(').Append(signature).Append(") => new ").Append(factory.ImplementationType)
			.Append('(').Append(arguments).AppendLine(");");
	}
}
