using System.Text;
using Awaiten.SourceGenerators.Entities;

namespace Awaiten.SourceGenerators;

/// <summary>
///     Emits the generated members of a container from its <see cref="ContainerModel" />: a base
///     <c>Scope</c> type holding the resolution logic (scoped instances, transient construction, synchronous
///     disposal) and a sealed <c>Root</c> subclass owning the thread-safe singletons. The <c>[Container]</c>
///     class itself is a static definition and carries no generated state. Enclosing types are re-opened as
///     <c>partial</c> so the container can be a nested type. Per-instance members are named after the
///     implementation type (e.g. <c>ResolveGreeter</c>, <c>_greeter</c>), with a numeric suffix added
///     only when two implementations would otherwise collide.
/// </summary>
internal static partial class Sources
{
	public static string Emit(ContainerModel model)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();

		int depth = 0;
		bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
		if (hasNamespace)
		{
			builder.Append("namespace ").AppendLine(model.Namespace);
			builder.AppendLine("{");
			depth++;
		}

		foreach (TypeDeclaration containing in model.ContainingTypes.AsArray())
		{
			Indent(builder, depth).Append("partial ").Append(containing.Keyword).Append(' ').AppendLine(containing.Name);
			Indent(builder, depth).AppendLine("{");
			depth++;
		}

		Indent(builder, depth).Append("static partial class ").AppendLine(model.TypeName);
		Indent(builder, depth).AppendLine("{");

		if (model.HasErrors)
		{
			EmitErrorBody(builder, depth + 1, model.TypeName, model.HasAsyncDisposable);
		}
		else
		{
			Names names = Names.Build(model.Instances.AsArray(), model.Collections.AsArray(), model.SyncResolveAfterInit);
			Dictionary<ServiceKey, int> serviceToIndex = BuildServiceMap(model);
			EmitContainerBody(builder, depth + 1, model, names, serviceToIndex);
		}

		Indent(builder, depth).AppendLine("}");

		for (int i = 0; i < model.ContainingTypes.Count; i++)
		{
			depth--;
			Indent(builder, depth).AppendLine("}");
		}

		if (hasNamespace)
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	/// <summary>
	///     The table-wide context shared by the resolver emitters: the full instance list, the name table, the
	///     service→index dispatch map, and whether the container emits the <c>IAsyncDisposable</c> surface.
	///     Threading these four as one value keeps the per-resolver signatures within the parameter budget (they
	///     otherwise travel together through every resolver).
	/// </summary>
	private readonly record struct EmitContext(
		InstanceModel[] Instances,
		Names Names,
		Dictionary<ServiceKey, int> ServiceToIndex,
		bool AsyncDisposal);

	private static void EmitContainerBody(StringBuilder builder, int depth, ContainerModel model, Names names, Dictionary<ServiceKey, int> serviceToIndex)
	{
		EmitContext context = new(model.Instances.AsArray(), names, serviceToIndex, model.HasAsyncDisposable);

		// The [Container] class is a pure static definition: it carries the registration attributes and any
		// static factory or instance members they name, and holds the generated Scope/Root types - nothing
		// generated lives on it directly. All state and resolution live on those types: the base Scope holds
		// the static dispatch table plus scoped/transient logic and delegates singletons to the root, while
		// the sealed Root subclass owns the singletons and is the usable instance (new MyContainer.Root()).
		EmitRootClass(builder, depth, context, model.SyncResolveAfterInit);
		builder.AppendLine();
		EmitScopeBaseClass(builder, depth, context, model.Strict, model.SyncResolveAfterInit, model.VarianceCandidates.AsArray());

		// The __AsyncArray<T> backing type for IAsyncEnumerable<T> collections is emitted on the container (a
		// private nested type reachable from both Scope and Root) only when the async collection materialization is
		// actually used - by an injection or by a by-type IAsyncEnumerable<T> dispatch entry / async resolver.
		if (NeedsAsyncArrayHelper(context.Instances, names, serviceToIndex))
		{
			builder.AppendLine();
			EmitAsyncArrayHelper(builder, depth);
		}
	}

	private static bool IsRootOwned(InstanceModel instance)
		=> instance.Lifetime == Lifetime.Singleton || instance.Production == ProductionKind.Instance;

	/// <summary>
	///     Whether synchronous resolution members (resolver, cache field, dispatch entries, typed fast path) are
	///     emitted for an instance: always for a non-tainted service, and for an async-tainted one only in
	///     pragmatic mode (SyncResolveAfterInit), where it may be resolved synchronously once InitializeAsync has
	///     warmed it. In the strict default an async-tainted service is reachable only through ResolveAsync.
	/// </summary>
	private static bool EmitsSync(InstanceModel instance, bool syncResolveAfterInit)
		=> !instance.IsAsyncTainted || syncResolveAfterInit;

	/// <summary>
	///     Emits the base <c>Scope</c>: the single home of resolution logic. It caches scoped instances on
	///     itself, constructs transients, and resolves singletons through <c>protected virtual</c> delegators
	///     that the <c>Root</c> subclass overrides. Child (request) scopes are instances of this type.
	/// </summary>
	private static void EmitScopeBaseClass(StringBuilder builder, int depth, EmitContext context, bool strict, bool syncResolveAfterInit, string[] varianceCandidates)
	{
		InstanceModel[] instances = context.Instances;
		Names names = context.Names;
		Dictionary<ServiceKey, int> serviceToIndex = context.ServiceToIndex;
		bool asyncDisposal = context.AsyncDisposal;

		AppendXmlSummary(builder, depth,
			"A resolution scope: caches scoped services and disposes the instances it created.");
		Indent(builder, depth).Append("public class Scope : global::Awaiten.IAwaitenScope, global::Awaiten.IExternalResolverHost");
		if (asyncDisposal)
		{
			// IAsyncDisposable is implemented on the concrete Scope (not added to the IAwaitenScope interface,
			// which would break every hand-implementer): the Root inherits it, and `await using` works on the
			// concrete container/scope. Emitted only when the compilation can see the type.
			builder.Append(", global::System.IAsyncDisposable");
		}

		EmitGenericResolverBases(builder, instances, strict, syncResolveAfterInit);
		builder.AppendLine();
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		// The dispatch table lives on the Scope (the only reader, through TryResolve); it is static, so it is
		// built once for the whole container, and reached by simple name from this type and its Root subclass.
		// Every entry is dispatchable; a root-withheld entry additionally appears in the __withheld table (its
		// guidance, thrown by Resolve on the Root) and carries the RootWithheld flag on its bucket slot (which
		// TryResolve consults only on the Root), so a child scope resolves it while the Root withholds it.
		List<DispatchEntry> entries = BuildDispatchEntries(instances, names, serviceToIndex, strict, syncResolveAfterInit);
		List<DispatchEntry> rootWithheld = Withheld(entries);
		// The __withheld guidance table merges two sources: the root-withheld disposable build-on-demand
		// services (still dispatchable from a child scope) and the async-tainted services excluded from
		// synchronous resolution entirely (reachable only through ResolveAsync). Both surface a helpful
		// message from Resolve instead of the generic "no registration"; only the former needs the
		// RootWithheld slot flag (it gates TryResolve on the Root), so that rides on the dispatch entries.
		List<(string Type, string Guidance)> withheldTypes = WithheldTypes(rootWithheld, instances, names, serviceToIndex, syncResolveAfterInit);
		if (entries.Count > 0)
		{
			// Data-driven by-type dispatch: a hand-tuned open-addressed table (keyed by Type identity hash) whose
			// slots carry the resolver delegate directly. The table grows in data, never in a single method's IL, so
			// it cannot exceed the JIT's optimization guards no matter how many registrations there are. The
			// root-withholding that used to live in a parallel __rootWithheld mask is folded into each slot.
			EmitBucketDispatch(builder, body, entries);
			builder.AppendLine();
		}

		if (withheldTypes.Count > 0)
		{
			EmitWithheldTable(builder, body, withheldTypes);
			builder.AppendLine();
		}

		// The (sealed) root scope this scope resolves singletons through. Holding the root directly lets a
		// child scope reach a singleton with a devirtualized call instead of a virtual override dispatch; it
		// is the root itself on the Root subclass, and shared down every child scope.
		Indent(builder, body).AppendLine("protected readonly Root __root;");
		// Synchronization is on a private gate object rather than the owner instance: a Scope/Root is
		// publicly reachable, and locking on it would let consumer code (lock (scope)) interfere with
		// resolution and disposal. The disposables list is created lazily on first use. These are protected
		// so the Root subclass's singleton overrides share the same gate and list.
		Indent(builder, body).AppendLine("protected readonly object __gate = new object();");
		Indent(builder, body).AppendLine("protected volatile bool __disposed;");
		Indent(builder, body).AppendLine("protected global::System.Collections.Generic.List<object>? __disposables;");
		if (NeedsWiringSupport(instances))
		{
			// The nesting depth of the wiring episode in progress on this owner (touched only under __gate; the
			// re-entrant resolves of a deferred cycle nest). The outermost frame commits every wiring flag - or
			// rolls a failed episode back - exactly once, so a nested participant is never flagged as wired while
			// an outer participant that references it is still half-wired.
			Indent(builder, body).AppendLine("protected int __wiring;");
		}

		EmitCacheFields(builder, body, instances, names, Lifetime.Scoped);
		builder.AppendLine();
		// The external resolver this scope routes its [FromServices] / [ImportServices] dependencies through
		// (IExternalResolverHost). A host wires each scope to its aligned provider; a child scope left without
		// one of its own falls back to the root's resolver in __ResolveExternal. Inherited by the Root, where it
		// is also the IAwaitenContainerMetadata.ExternalResolver a host sets for the singleton (root) path.
		Indent(builder, body).AppendLine("public global::Awaiten.IExternalResolver? ExternalResolver { get; set; }");
		builder.AppendLine();
		// The root is its own __root (this parameterless ctor is only ever reached through Root's base call,
		// so the cast always holds); child scopes are handed the shared root. The child ctor is private so a
		// scope is only ever created through CreateScope(), never hand-built with a borrowed root.
		Indent(builder, body).AppendLine("private protected Scope()");
		Indent(builder, body).AppendLine("{");
		Indent(builder, body + 1).AppendLine("__root = (Root)this;");
		Indent(builder, body).AppendLine("}");
		builder.AppendLine();
		Indent(builder, body).AppendLine("private Scope(Root root)");
		Indent(builder, body).AppendLine("{");
		Indent(builder, body + 1).AppendLine("__root = root;");
		Indent(builder, body).AppendLine("}");
		builder.AppendLine();
		EmitResolutionApi(builder, body, context, strict, syncResolveAfterInit, varianceCandidates);
		builder.AppendLine();
		EmitGenericResolveMethod(builder, body);
		builder.AppendLine();
		// The asynchronous surface: ResolveAsync(Type) on every owner, plus the IAwaitenScope members
		// InitializeAsync (the base warms this scope's async scoped services; the Root overrides it to warm
		// the singletons) and CreateScopeAsync. The Root's per-singleton async resolvers are emitted there.
		EmitAsyncResolutionApi(builder, body, instances, names, serviceToIndex, strict, syncResolveAfterInit);
		builder.AppendLine();
		EmitScopeInitializeAsync(builder, body, instances, names);
		builder.AppendLine();
		EmitCreateScopeAsync(builder, body);
		builder.AppendLine();
		// A scope is the single source of scopes: nesting shares the same root (and therefore the same
		// singletons), so a child created from a child is no different from one created from the root. A
		// child scope's lifetime is owned by its caller; the parent does not track it. The concrete return
		// type spares callers holding a Scope an interface hop; the interface contract is met explicitly.
		AppendXmlSummary(builder, body,
			"Opens a child scope; the caller owns and disposes it.");
		Indent(builder, body).AppendLine("public Scope CreateScope() => new Scope(__root);");
		Indent(builder, body).AppendLine("global::Awaiten.IAwaitenScope global::Awaiten.IAwaitenScope.CreateScope() => CreateScope();");

		if (instances.Length > 0)
		{
			builder.AppendLine();
			EmitOwnedHelper(builder, body, HasExternalDependencies(instances));
		}

		// The __ResolveExternal helper is emitted on the base Scope (reached from the Root through __root) only
		// when the container actually has [FromServices] / [ImportServices] dependencies, so a container without
		// them carries no unused helper.
		if (HasExternalDependencies(instances))
		{
			builder.AppendLine();
			EmitResolveExternal(builder, body);
		}

		builder.AppendLine();
		EmitGenericResolverImpls(builder, body, instances, names, strict, syncResolveAfterInit);

		EmitInstanceResolvers(builder, body, context, instances, names, syncResolveAfterInit);

		// The async by-type resolver for each async collection (one whose IAsyncEnumerable<T> shape ResolveAsync
		// serves through the async dispatch arm added in EmitAsyncResolutionApi).
		foreach ((ServiceMembers collection, string method) in AsyncByTypeCollections(names, serviceToIndex, syncResolveAfterInit))
		{
			builder.AppendLine();
			EmitAsyncCollectionResolver(builder, body, collection, method, names, instances);
		}

		if (NeedsWiringSupport(instances))
		{
			builder.AppendLine();
			EmitWiringSupport(builder, body, instances, names, root: false);
		}

		builder.AppendLine();
		EmitDispose(builder, body, asyncDisposal);

		if (asyncDisposal)
		{
			builder.AppendLine();
			EmitDisposeAsync(builder, body);
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits each instance's per-service resolvers into the Scope body: a synchronous resolver - suppressed for
	///     an async-tainted service in the strict default (reachable only through ResolveAsync), and in pragmatic
	///     mode delegating to the memoizing async resolver rather than constructing a second, uninitialized instance
	///     (a parameterized service forwarding its runtime arguments), so there is a single init path - and, for
	///     every async-tainted service, its async resolver.
	/// </summary>
	private static void EmitInstanceResolvers(StringBuilder builder, int depth, EmitContext context, InstanceModel[] instances, Names names, bool syncResolveAfterInit)
	{
		for (int i = 0; i < instances.Length; i++)
		{
			if (EmitsSync(instances[i], syncResolveAfterInit))
			{
				builder.AppendLine();
				if (instances[i].IsAsyncTainted)
				{
					EmitDelegatingSyncResolver(builder, depth, i, instances[i], names);
				}
				else
				{
					EmitScopeResolver(builder, depth, i, context);
				}
			}

			if (instances[i].IsAsyncTainted)
			{
				builder.AppendLine();
				EmitAsyncScopeResolver(builder, depth, i, context);
			}
		}
	}

	/// <summary>
	///     Whether the container needs the deferred-wiring episode machinery (the <c>__wiring</c> depth counter
	///     and the <c>__CommitWiring</c>/<c>__RollbackWiring</c> pair): some synchronously-cached instance has a
	///     deferred (<c>[Inject(Deferred = true)]</c>) member, so its cache-miss block runs a wiring episode.
	/// </summary>
	private static bool NeedsWiringSupport(InstanceModel[] instances)
		=> instances.Any(instance => IsSyncCachedDeferred(instance, Lifetime.Singleton) || IsSyncCachedDeferred(instance, Lifetime.Scoped));

	/// <summary>
	///     Whether the instance is cached by a synchronous caching resolver of the given lifetime <em>and</em> has
	///     deferred members - exactly the instances that get a volatile wiring flag (see
	///     <see cref="EmitCacheFields" />) and participate in wiring episodes.
	/// </summary>
	private static bool IsSyncCachedDeferred(InstanceModel instance, Lifetime lifetime)
		=> instance.Lifetime == lifetime
		   && instance.Production != ProductionKind.Instance
		   && !instance.IsParameterized
		   && !instance.IsAsyncTainted
		   && HasDeferredMembers(instance);

	/// <summary>
	///     Emits the wiring-episode commit/rollback pair over the owner's deferred-member instances (the scoped
	///     ones on the base <c>Scope</c>, plus the singletons in the <c>Root</c> override). The outermost frame of
	///     a wiring episode calls <c>__CommitWiring</c> on success - flagging every instance the episode published
	///     as fully wired, so the lock-free fast paths may hand them out - and <c>__RollbackWiring</c> on failure,
	///     unpublishing every instance the failed episode left half-wired so the next resolve rebuilds it. The pair
	///     is virtual because an episode on the <c>Root</c> can span its inherited scoped instances and its
	///     singletons under the same gate, so the Root override must flush both sets.
	/// </summary>
	private static void EmitWiringSupport(StringBuilder builder, int depth, InstanceModel[] instances, Names names, bool root)
	{
		string modifiers = root ? "private protected override" : "private protected virtual";
		Lifetime lifetime = root ? Lifetime.Singleton : Lifetime.Scoped;

		AppendXmlSummary(builder, depth,
			"Marks every published deferred-member instance as fully wired: called by the outermost frame of a",
			"successful wiring episode, so a half-wired instance is never observable through the lock-free fast",
			"path - not even transitively through an already-published peer.");
		Indent(builder, depth).Append(modifiers).AppendLine(" void __CommitWiring()");
		Indent(builder, depth).AppendLine("{");
		if (root)
		{
			Indent(builder, depth + 1).AppendLine("base.__CommitWiring();");
		}

		for (int i = 0; i < instances.Length; i++)
		{
			if (IsSyncCachedDeferred(instances[i], lifetime))
			{
				Indent(builder, depth + 1).Append("if (").Append(names.Field(i)).AppendLine(" is not null)");
				Indent(builder, depth + 1).AppendLine("{");
				Indent(builder, depth + 2).Append(names.WiredField(i)).AppendLine(" = true;");
				Indent(builder, depth + 1).AppendLine("}");
			}
		}

		Indent(builder, depth).AppendLine("}");
		builder.AppendLine();

		AppendXmlSummary(builder, depth,
			"Unpublishes every instance a failed wiring episode left half-wired (published, wiring flag still",
			"false), so the next resolve rebuilds it instead of silently returning a half-wired instance.");
		Indent(builder, depth).Append(modifiers).AppendLine(" void __RollbackWiring()");
		Indent(builder, depth).AppendLine("{");
		if (root)
		{
			Indent(builder, depth + 1).AppendLine("base.__RollbackWiring();");
		}

		for (int i = 0; i < instances.Length; i++)
		{
			if (IsSyncCachedDeferred(instances[i], lifetime))
			{
				Indent(builder, depth + 1).Append("if (!").Append(names.WiredField(i)).AppendLine(")");
				Indent(builder, depth + 1).AppendLine("{");
				Indent(builder, depth + 2).Append(names.Field(i)).AppendLine(" = null;");
				Indent(builder, depth + 1).AppendLine("}");
			}
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the <c>Root</c>: the root scope where singletons (and pre-built Instances) physically live,
	///     and the usable container instance (<c>new MyContainer.Root()</c>). It overrides the base's virtual
	///     singleton delegators with the real caching/member access, so a child scope delegating through
	///     <c>__root</c> lands here.
	/// </summary>
	private static void EmitRootClass(StringBuilder builder, int depth, EmitContext context, bool syncResolveAfterInit)
	{
		InstanceModel[] instances = context.Instances;
		Names names = context.Names;

		// The Root is the composition root (IAwaitenContainerMetadata, which is an IAwaitenRoot): it adds
		// InitializeAsync to warm the singletons and advertises its registrations for the MS.DI bridge. A
		// child scope is only an IAwaitenScope - it is warmed when created (CreateScopeAsync), never explicitly.
		AppendXmlSummary(builder, depth,
			"The container root: owns the singleton instances and serves as the default scope.");
		Indent(builder, depth).AppendLine("public sealed class Root : Scope, global::Awaiten.IAwaitenContainerMetadata");
		Indent(builder, depth).AppendLine("{");
		int body = depth + 1;

		EmitCacheFields(builder, body, instances, names, Lifetime.Singleton);
		builder.AppendLine();
		Indent(builder, body).AppendLine("public Root() : base()");
		Indent(builder, body).AppendLine("{");
		Indent(builder, body).AppendLine("}");
		builder.AppendLine();
		EmitRegistrations(builder, body, instances, syncResolveAfterInit);
		builder.AppendLine();
		// The external-dependency metadata (advertised list + the host-settable resolver) that the
		// IAwaitenContainerMetadata surface requires; the list is empty when the container has none.
		EmitExternalMetadata(builder, body, instances);
		builder.AppendLine();
		// The Root override of InitializeAsync warms the async singletons in dependency order (the base
		// Scope warms only its async scoped services).
		EmitRootInitializeAsync(builder, body, instances, names);

		// The Root's wiring commit/rollback override adds the deferred singletons to the base Scope's scoped
		// set: an episode on the Root (whose gate its singleton resolvers and inherited scoped resolvers share)
		// can publish both kinds, so the outermost frame must flush both.
		if (instances.Any(instance => IsSyncCachedDeferred(instance, Lifetime.Singleton)))
		{
			builder.AppendLine();
			EmitWiringSupport(builder, body, instances, names, root: true);
		}

		for (int i = 0; i < instances.Length; i++)
		{
			InstanceModel instance = instances[i];
			// A parameterized service is never cached on the root; its single fresh-per-call resolver lives
			// on the base Scope (protected) and the Root inherits it. Only singleton-owned instances
			// (singletons and pre-built Instances) get a Root override.
			if (instance.IsParameterized
			    || (instance.Lifetime != Lifetime.Singleton && instance.Production != ProductionKind.Instance))
			{
				continue;
			}

			// The synchronous override is suppressed for an async-tainted singleton: in the strict default it
			// is reachable only through ResolveAsync, and in pragmatic mode its synchronous resolver is the
			// base Scope's delegator to the async path (which the async override below backs), so it needs no
			// Root sync override of its own.
			if (EmitsSync(instance, syncResolveAfterInit) && !instance.IsAsyncTainted)
			{
				builder.AppendLine();
				EmitRootResolver(builder, body, i, context);
			}

			if (instance.IsAsyncTainted)
			{
				builder.AppendLine();
				EmitAsyncRootResolver(builder, body, i, context);
			}
		}

		Indent(builder, depth).AppendLine("}");
	}

	/// <summary>
	///     Emits the volatile cache fields for instances of the given lifetime (reference-type fields are
	///     volatile so the lock-free fast path cannot observe a non-null reference before the constructor's
	///     writes are visible on weak memory models such as arm64). A pre-built Instance has no field.
	/// </summary>
	private static void EmitCacheFields(StringBuilder builder, int depth, InstanceModel[] instances, Names names, Lifetime lifetime)
	{
		for (int i = 0; i < instances.Length; i++)
		{
			InstanceModel instance = instances[i];
			// A pre-built Instance has no field, and a parameterized service is rebuilt per call from its
			// runtime arguments and so is never cached.
			if (instance.Production == ProductionKind.Instance || instance.IsParameterized || instance.Lifetime != lifetime)
			{
				continue;
			}

			// The synchronous cache backs synchronous resolution. An async-tainted service is never cached
			// synchronously: in the strict default it has no synchronous resolver at all, and in pragmatic
			// mode its synchronous resolver delegates to the (memoizing) async one - so the async cache below
			// is its single home and there is no second, uninitialized instance to cache here.
			if (!instance.IsAsyncTainted)
			{
				string modifier = instance.IsReferenceType ? "private volatile " : "private ";
				Indent(builder, depth).Append(modifier).Append(instance.ConstructedType)
					.Append("? ").Append(names.Field(i)).AppendLine(";");

				// A deferred ([Inject(Deferred = true)]) member is wired after the cache field is published, so a
				// separate volatile flag marks when wiring has completed. The lock-free fast path gates on it (rather
				// than on the field alone) so a concurrent caller never returns a published-but-half-wired instance,
				// while the mid-wiring re-entrant resolve sees it still false, skips the fast path and terminates the
				// cycle through the reentrant lock. It is committed by the outermost frame of the wiring episode
				// (__CommitWiring), so a cycle peer is never flagged while a participant that references it is still
				// half-wired. Volatile: its release-write happens-after every deferred write of the episode, so a
				// reader that acquire-reads it as true sees fully-wired instances only.
				if (HasDeferredMembers(instance))
				{
					Indent(builder, depth).Append("private volatile bool ").Append(names.WiredField(i)).AppendLine(";");
				}
			}

			// The async cache memoizes the construction-and-initialization Task so it is awaited exactly
			// once; it is volatile so the lock-free read cannot observe it before its writes are visible.
			if (instance.IsAsyncTainted)
			{
				Indent(builder, depth).Append("private volatile global::System.Threading.Tasks.Task<").Append(instance.ConstructedType)
					.Append(">? ").Append(names.AsyncField(i)).AppendLine(";");
			}
		}
	}

	private static void EmitErrorBody(StringBuilder builder, int depth, string typeName, bool asyncDisposal)
	{
		string message =
			$"\"Awaiten: container '{typeName}' has registration errors; see the build diagnostics (AWT1xx).\"";
		// The container has registration errors, so emit a throwing Root that still satisfies the shape
		// consumers depend on (new MyContainer.Root(), Resolve, CreateScope, InitializeAsync, Dispose). This
		// keeps the build focused on the actionable AWT diagnostics rather than cascading "type not found"
		// errors. It implements IAwaitenContainerMetadata (which includes IAwaitenRoot and IAwaitenScope),
		// matching the real Root - and, when IAsyncDisposable is available, that too (the real Root implements it
		// concretely), so `await using` over the stub compiles the same way.
		Indent(builder, depth).Append("public sealed class Root : global::Awaiten.IAwaitenContainerMetadata");
		if (asyncDisposal)
		{
			builder.Append(", global::System.IAsyncDisposable");
		}

		builder.AppendLine();
		Indent(builder, depth).AppendLine("{");
		Indent(builder, depth + 1).Append(
				"public object Resolve(global::System.Type serviceType) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public bool TryResolve(global::System.Type serviceType, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out object? instance)");
		Indent(builder, depth + 1).AppendLine("{");
		Indent(builder, depth + 2).AppendLine("instance = null;");
		Indent(builder, depth + 2).AppendLine("return false;");
		Indent(builder, depth + 1).AppendLine("}");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::Awaiten.IAwaitenScope CreateScope() => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::System.Threading.Tasks.Task<object> ResolveAsync(global::System.Type serviceType, global::System.Threading.CancellationToken cancellationToken = default) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::System.Threading.Tasks.Task InitializeAsync(global::System.Threading.CancellationToken cancellationToken = default) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).Append(
				"public global::System.Threading.Tasks.Task<global::Awaiten.IAwaitenScope> CreateScopeAsync(global::System.Threading.CancellationToken cancellationToken = default) => throw new global::System.InvalidOperationException(")
			.Append(message).AppendLine(");");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public void Dispose() { }");
		if (asyncDisposal)
		{
			builder.AppendLine();
			Indent(builder, depth + 1).AppendLine("public global::System.Threading.Tasks.ValueTask DisposeAsync() => default;");
		}

		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("global::System.Collections.Generic.IReadOnlyList<global::Awaiten.AwaitenRegistration> global::Awaiten.IAwaitenContainerMetadata.Registrations => global::System.Array.Empty<global::Awaiten.AwaitenRegistration>();");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("global::System.Collections.Generic.IReadOnlyList<global::Awaiten.AwaitenExternalDependency> global::Awaiten.IAwaitenContainerMetadata.ExternalDependencies => global::System.Array.Empty<global::Awaiten.AwaitenExternalDependency>();");
		builder.AppendLine();
		Indent(builder, depth + 1).AppendLine("public global::Awaiten.IExternalResolver? ExternalResolver { get; set; }");

		Indent(builder, depth).AppendLine("}");
	}

	private static StringBuilder Indent(StringBuilder builder, int depth)
	{
		for (int i = 0; i < depth; i++)
		{
			builder.Append('\t');
		}

		return builder;
	}

	/// <summary>
	///     Appends an XML <c>///</c> summary doc comment over the following generated member, one indented
	///     line per entry in <paramref name="lines" />.
	/// </summary>
	private static void AppendXmlSummary(StringBuilder builder, int depth, params string[] lines)
	{
		Indent(builder, depth).AppendLine("/// <summary>");
		foreach (string line in lines)
		{
			Indent(builder, depth).Append("///     ").AppendLine(line);
		}

		Indent(builder, depth).AppendLine("/// </summary>");
	}

	/// <summary>
	///     A doc-comment reference to a type in the generated code: a <c>&lt;see cref="…" /&gt;</c> for a
	///     plain fully-qualified name, and an escaped <c>&lt;c&gt;…&lt;/c&gt;</c> for a constructed generic
	///     type (which is not a valid <c>cref</c> target).
	/// </summary>
	private static string XmlTypeRef(string type)
		=> type.IndexOf('<') < 0
			? $"<see cref=\"{type}\" />"
			: $"<c>{type.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")}</c>";
}
